/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 */

 /**
 * @file models.hpp
 * @brief expose lance_namespace_rest_client::model as lance_namespace::models
 */

#pragma once

#include "lance_namespace_rest_client/HttpContent.h"
#include "lance_namespace_rest_client/IHttpBody.h"
#include "lance_namespace_rest_client/JsonBody.h"
#include "lance_namespace_rest_client/ModelBase.h"
#include "lance_namespace_rest_client/MultipartFormData.h"
#include "lance_namespace_rest_client/Object.h"
#include "lance_namespace_rest_client/model/AddColumnsEntry.h"
#include "lance_namespace_rest_client/model/AddVirtualColumnEntry.h"
#include "lance_namespace_rest_client/model/AddVirtualColumnOutputEntry.h"
#include "lance_namespace_rest_client/model/AlterColumnsEntry.h"
#include "lance_namespace_rest_client/model/AlterTableAddColumnsRequest.h"
#include "lance_namespace_rest_client/model/AlterTableAddColumnsResponse.h"
#include "lance_namespace_rest_client/model/AlterTableAlterColumnsRequest.h"
#include "lance_namespace_rest_client/model/AlterTableAlterColumnsResponse.h"
#include "lance_namespace_rest_client/model/AlterTableBackfillColumnsRequest.h"
#include "lance_namespace_rest_client/model/AlterTableBackfillColumnsResponse.h"
#include "lance_namespace_rest_client/model/AlterTableDropColumnsRequest.h"
#include "lance_namespace_rest_client/model/AlterTableDropColumnsResponse.h"
#include "lance_namespace_rest_client/model/AlterTransactionAction.h"
#include "lance_namespace_rest_client/model/AlterTransactionRequest.h"
#include "lance_namespace_rest_client/model/AlterTransactionResponse.h"
#include "lance_namespace_rest_client/model/AlterTransactionSetProperty.h"
#include "lance_namespace_rest_client/model/AlterTransactionSetStatus.h"
#include "lance_namespace_rest_client/model/AlterTransactionUnsetProperty.h"
#include "lance_namespace_rest_client/model/AlterVirtualColumnEntry.h"
#include "lance_namespace_rest_client/model/AnalyzeTableQueryPlanRequest.h"
#include "lance_namespace_rest_client/model/AnalyzeTableQueryPlanResponse.h"
#include "lance_namespace_rest_client/model/BatchCommitTablesRequest.h"
#include "lance_namespace_rest_client/model/BatchCommitTablesResponse.h"
#include "lance_namespace_rest_client/model/BatchCreateTableVersionsRequest.h"
#include "lance_namespace_rest_client/model/BatchCreateTableVersionsResponse.h"
#include "lance_namespace_rest_client/model/BatchDeleteTableVersionsRequest.h"
#include "lance_namespace_rest_client/model/BatchDeleteTableVersionsResponse.h"
#include "lance_namespace_rest_client/model/CommitTableOperation.h"
#include "lance_namespace_rest_client/model/CommitTableResult.h"
#include "lance_namespace_rest_client/model/CountTableRowsRequest.h"
#include "lance_namespace_rest_client/model/CreateMaterializedViewRequest.h"
#include "lance_namespace_rest_client/model/CreateMaterializedViewResponse.h"
#include "lance_namespace_rest_client/model/CreateNamespaceRequest.h"
#include "lance_namespace_rest_client/model/CreateNamespaceResponse.h"
#include "lance_namespace_rest_client/model/CreateTableBranchRequest.h"
#include "lance_namespace_rest_client/model/CreateTableBranchResponse.h"
#include "lance_namespace_rest_client/model/CreateTableIndexRequest.h"
#include "lance_namespace_rest_client/model/CreateTableIndexResponse.h"
#include "lance_namespace_rest_client/model/CreateTableRequest.h"
#include "lance_namespace_rest_client/model/CreateTableResponse.h"
#include "lance_namespace_rest_client/model/CreateTableScalarIndexResponse.h"
#include "lance_namespace_rest_client/model/CreateTableTagRequest.h"
#include "lance_namespace_rest_client/model/CreateTableTagResponse.h"
#include "lance_namespace_rest_client/model/CreateTableVersionRequest.h"
#include "lance_namespace_rest_client/model/CreateTableVersionResponse.h"
#include "lance_namespace_rest_client/model/DeclareTableRequest.h"
#include "lance_namespace_rest_client/model/DeclareTableResponse.h"
#include "lance_namespace_rest_client/model/DeleteFromTableRequest.h"
#include "lance_namespace_rest_client/model/DeleteFromTableResponse.h"
#include "lance_namespace_rest_client/model/DeleteTableBranchRequest.h"
#include "lance_namespace_rest_client/model/DeleteTableBranchResponse.h"
#include "lance_namespace_rest_client/model/DeleteTableTagRequest.h"
#include "lance_namespace_rest_client/model/DeleteTableTagResponse.h"
#include "lance_namespace_rest_client/model/DeregisterTableRequest.h"
#include "lance_namespace_rest_client/model/DeregisterTableResponse.h"
#include "lance_namespace_rest_client/model/DescribeNamespaceRequest.h"
#include "lance_namespace_rest_client/model/DescribeNamespaceResponse.h"
#include "lance_namespace_rest_client/model/DescribeTableIndexStatsRequest.h"
#include "lance_namespace_rest_client/model/DescribeTableIndexStatsResponse.h"
#include "lance_namespace_rest_client/model/DescribeTableRequest.h"
#include "lance_namespace_rest_client/model/DescribeTableResponse.h"
#include "lance_namespace_rest_client/model/DescribeTableVersionRequest.h"
#include "lance_namespace_rest_client/model/DescribeTableVersionResponse.h"
#include "lance_namespace_rest_client/model/DescribeTransactionRequest.h"
#include "lance_namespace_rest_client/model/DescribeTransactionResponse.h"
#include "lance_namespace_rest_client/model/DropNamespaceRequest.h"
#include "lance_namespace_rest_client/model/DropNamespaceResponse.h"
#include "lance_namespace_rest_client/model/DropTableIndexRequest.h"
#include "lance_namespace_rest_client/model/DropTableIndexResponse.h"
#include "lance_namespace_rest_client/model/DropTableRequest.h"
#include "lance_namespace_rest_client/model/DropTableResponse.h"
#include "lance_namespace_rest_client/model/ExplainTableQueryPlanRequest.h"
#include "lance_namespace_rest_client/model/ExplainTableQueryPlanResponse.h"
#include "lance_namespace_rest_client/model/GetTableStatsRequest.h"
#include "lance_namespace_rest_client/model/GetTableStatsResponse.h"
#include "lance_namespace_rest_client/model/GetTableTagVersionRequest.h"
#include "lance_namespace_rest_client/model/GetTableTagVersionResponse.h"
#include "lance_namespace_rest_client/model/InsertIntoTableRequest.h"
#include "lance_namespace_rest_client/model/InsertIntoTableResponse.h"
#include "lance_namespace_rest_client/model/ListNamespacesRequest.h"
#include "lance_namespace_rest_client/model/ListNamespacesResponse.h"
#include "lance_namespace_rest_client/model/ListTableBranchesRequest.h"
#include "lance_namespace_rest_client/model/ListTableBranchesResponse.h"
#include "lance_namespace_rest_client/model/ListTableIndicesRequest.h"
#include "lance_namespace_rest_client/model/ListTableIndicesResponse.h"
#include "lance_namespace_rest_client/model/ListTableTagsRequest.h"
#include "lance_namespace_rest_client/model/ListTableTagsResponse.h"
#include "lance_namespace_rest_client/model/ListTableVersionsRequest.h"
#include "lance_namespace_rest_client/model/ListTableVersionsResponse.h"
#include "lance_namespace_rest_client/model/ListTablesRequest.h"
#include "lance_namespace_rest_client/model/ListTablesResponse.h"
#include "lance_namespace_rest_client/model/MatchQuery.h"
#include "lance_namespace_rest_client/model/MaterializedViewUdtfEntry.h"
#include "lance_namespace_rest_client/model/NamespaceExistsRequest.h"
#include "lance_namespace_rest_client/model/PartitionField.h"
#include "lance_namespace_rest_client/model/PartitionSpec.h"
#include "lance_namespace_rest_client/model/PartitionTransform.h"
#include "lance_namespace_rest_client/model/PhraseQuery.h"
#include "lance_namespace_rest_client/model/QueryTableRequest.h"
#include "lance_namespace_rest_client/model/QueryTableRequest_columns.h"
#include "lance_namespace_rest_client/model/QueryTableRequest_full_text_query.h"
#include "lance_namespace_rest_client/model/QueryTableRequest_vector.h"
#include "lance_namespace_rest_client/model/RefreshMaterializedViewRequest.h"
#include "lance_namespace_rest_client/model/RefreshMaterializedViewResponse.h"
#include "lance_namespace_rest_client/model/RegisterTableRequest.h"
#include "lance_namespace_rest_client/model/RegisterTableResponse.h"
#include "lance_namespace_rest_client/model/RenameTableRequest.h"
#include "lance_namespace_rest_client/model/RenameTableResponse.h"
#include "lance_namespace_rest_client/model/RestoreTableRequest.h"
#include "lance_namespace_rest_client/model/RestoreTableResponse.h"
#include "lance_namespace_rest_client/model/TableBasicStats.h"
#include "lance_namespace_rest_client/model/TableExistsRequest.h"
#include "lance_namespace_rest_client/model/TableVersion.h"
#include "lance_namespace_rest_client/model/TagContents.h"
#include "lance_namespace_rest_client/model/UpdateFieldMetadataEntry.h"
#include "lance_namespace_rest_client/model/UpdateFieldMetadataRequest.h"
#include "lance_namespace_rest_client/model/UpdateFieldMetadataResponse.h"
#include "lance_namespace_rest_client/model/UpdateTableRequest.h"
#include "lance_namespace_rest_client/model/UpdateTableResponse.h"
#include "lance_namespace_rest_client/model/UpdateTableSchemaMetadataRequest.h"
#include "lance_namespace_rest_client/model/UpdateTableSchemaMetadataResponse.h"
#include "lance_namespace_rest_client/model/UpdateTableTagRequest.h"
#include "lance_namespace_rest_client/model/UpdateTableTagResponse.h"
#include "lance_namespace_rest_client/model/VersionRange.h"
namespace lance_namespace {

namespace models = org::openapitools::client::model;

}  // namespace lance_namespace
