/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BatchCreateTableVersionsRequest.h
 *
 * Request to atomically create new version entries for multiple tables. The operation is atomic: all versions are created or none are. 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_BatchCreateTableVersionsRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_BatchCreateTableVersionsRequest_H_


#include "lance_namespace_rest_client/ModelBase.h"

#include "lance_namespace_rest_client/model/CreateTableVersionEntry.h"
#include "lance_namespace_rest_client/model/Identity.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Identity;
class CreateTableVersionEntry;


/// <summary>
/// Request to atomically create new version entries for multiple tables. The operation is atomic: all versions are created or none are. 
/// </summary>
class  BatchCreateTableVersionsRequest
    : public ModelBase
{
public:
    BatchCreateTableVersionsRequest();
    virtual ~BatchCreateTableVersionsRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// BatchCreateTableVersionsRequest members


    std::shared_ptr<Identity> getIdentity() const;
    bool identityIsSet() const;
    void unsetIdentity();
    void setIdentity(const std::shared_ptr<Identity>& value);

    /// <summary>
    /// Arbitrary context for a request as key-value pairs. How to use the context is custom to the specific implementation.  REST NAMESPACE ONLY Context entries are passed via HTTP headers using the naming convention &#x60;x-lance-ctx-&lt;key&gt;: &lt;value&gt;&#x60;. For example, a context entry &#x60;{\&quot;trace_id\&quot;: \&quot;abc123\&quot;}&#x60; would be sent as the header &#x60;x-lance-ctx-trace_id: abc123&#x60;. 
    /// </summary>
    std::map<utility::string_t, utility::string_t> getContext() const;
    bool contextIsSet() const;
    void unsetContext();
    void setContext(const std::map<utility::string_t, utility::string_t>& value);

    /// <summary>
    /// List of table version entries to create atomically
    /// </summary>
    std::vector<std::shared_ptr<CreateTableVersionEntry>> getEntries() const;
    bool entriesIsSet() const;
    void unsetEntries();
    void setEntries(const std::vector<std::shared_ptr<CreateTableVersionEntry>>& value);


protected:
    std::shared_ptr<Identity> m_Identity;
    bool m_IdentityIsSet;

    std::map<utility::string_t, utility::string_t> m_Context;
    bool m_ContextIsSet;

    std::vector<std::shared_ptr<CreateTableVersionEntry>> m_Entries;
    bool m_EntriesIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_BatchCreateTableVersionsRequest_H_ */
