/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FragmentStats.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_FragmentStats_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_FragmentStats_H_


#include "lance_namespace_rest_client/ModelBase.h"

#include "lance_namespace_rest_client/model/FragmentSummary.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class FragmentSummary;


class  FragmentStats
    : public ModelBase
{
public:
    FragmentStats();
    virtual ~FragmentStats();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// FragmentStats members


    /// <summary>
    /// The number of fragments in the table
    /// </summary>
    int64_t getNumFragments() const;
    bool numFragmentsIsSet() const;
    void unsetNum_fragments();
    void setNumFragments(int64_t value);

    /// <summary>
    /// The number of uncompacted fragments in the table
    /// </summary>
    int64_t getNumSmallFragments() const;
    bool numSmallFragmentsIsSet() const;
    void unsetNum_small_fragments();
    void setNumSmallFragments(int64_t value);

    /// <summary>
    /// Statistics on the number of rows in the table fragments
    /// </summary>
    std::shared_ptr<FragmentSummary> getLengths() const;
    bool lengthsIsSet() const;
    void unsetLengths();
    void setLengths(const std::shared_ptr<FragmentSummary>& value);


protected:
    int64_t m_Num_fragments;
    bool m_Num_fragmentsIsSet;

    int64_t m_Num_small_fragments;
    bool m_Num_small_fragmentsIsSet;

    std::shared_ptr<FragmentSummary> m_Lengths;
    bool m_LengthsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_FragmentStats_H_ */
