/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MergeInsertIntoTableResponse.h
 *
 * Response from merge insert operation
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MergeInsertIntoTableResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MergeInsertIntoTableResponse_H_


#include "lance_namespace_rest_client/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Response from merge insert operation
/// </summary>
class  MergeInsertIntoTableResponse
    : public ModelBase
{
public:
    MergeInsertIntoTableResponse();
    virtual ~MergeInsertIntoTableResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// MergeInsertIntoTableResponse members


    /// <summary>
    /// Optional transaction identifier
    /// </summary>
    utility::string_t getTransactionId() const;
    bool transactionIdIsSet() const;
    void unsetTransaction_id();
    void setTransactionId(const utility::string_t& value);

    /// <summary>
    /// Number of rows updated
    /// </summary>
    int64_t getNumUpdatedRows() const;
    bool numUpdatedRowsIsSet() const;
    void unsetNum_updated_rows();
    void setNumUpdatedRows(int64_t value);

    /// <summary>
    /// Number of rows inserted
    /// </summary>
    int64_t getNumInsertedRows() const;
    bool numInsertedRowsIsSet() const;
    void unsetNum_inserted_rows();
    void setNumInsertedRows(int64_t value);

    /// <summary>
    /// Number of rows deleted (typically 0 for merge insert)
    /// </summary>
    int64_t getNumDeletedRows() const;
    bool numDeletedRowsIsSet() const;
    void unsetNum_deleted_rows();
    void setNumDeletedRows(int64_t value);

    /// <summary>
    /// The commit version associated with the operation
    /// </summary>
    int64_t getVersion() const;
    bool versionIsSet() const;
    void unsetVersion();
    void setVersion(int64_t value);


protected:
    utility::string_t m_Transaction_id;
    bool m_Transaction_idIsSet;

    int64_t m_Num_updated_rows;
    bool m_Num_updated_rowsIsSet;

    int64_t m_Num_inserted_rows;
    bool m_Num_inserted_rowsIsSet;

    int64_t m_Num_deleted_rows;
    bool m_Num_deleted_rowsIsSet;

    int64_t m_Version;
    bool m_VersionIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MergeInsertIntoTableResponse_H_ */
