/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PhraseQuery.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PhraseQuery_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PhraseQuery_H_


#include "lance_namespace_rest_client/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  PhraseQuery
    : public ModelBase
{
public:
    PhraseQuery();
    virtual ~PhraseQuery();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// PhraseQuery members


    /// <summary>
    /// Lance field path to match. Nested fields use dot-separated segments; use backtick-quoted segments for literal dots and double backticks inside quoted segments. Omit to use the query default fields.
    /// </summary>
    utility::string_t getColumn() const;
    bool columnIsSet() const;
    void unsetColumn();
    void setColumn(const utility::string_t& value);

    int32_t getSlop() const;
    bool slopIsSet() const;
    void unsetSlop();
    void setSlop(int32_t value);

    utility::string_t getTerms() const;
    bool termsIsSet() const;
    void unsetTerms();
    void setTerms(const utility::string_t& value);


protected:
    utility::string_t m_Column;
    bool m_ColumnIsSet;

    int32_t m_Slop;
    bool m_SlopIsSet;

    utility::string_t m_Terms;
    bool m_TermsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PhraseQuery_H_ */
