/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UpdateFieldMetadataEntry.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateFieldMetadataEntry_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateFieldMetadataEntry_H_


#include "lance_namespace_rest_client/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <map>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  UpdateFieldMetadataEntry
    : public ModelBase
{
public:
    UpdateFieldMetadataEntry();
    virtual ~UpdateFieldMetadataEntry();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// UpdateFieldMetadataEntry members


    /// <summary>
    /// Lance field path whose metadata to update. Nested fields use dot-separated segments; use backtick-quoted segments for literal dots and double backticks inside quoted segments. Use canonical full paths for display and errors; leaf names alone only identify top-level fields; invalid or unresolved paths should return InvalidInput or TableColumnNotFound.
    /// </summary>
    utility::string_t getPath() const;
    bool pathIsSet() const;
    void unsetPath();
    void setPath(const utility::string_t& value);

    /// <summary>
    /// Metadata key-value pairs to apply to the field. A null value deletes that key. 
    /// </summary>
    std::map<utility::string_t, utility::string_t> getMetadata() const;
    bool metadataIsSet() const;
    void unsetMetadata();
    void setMetadata(const std::map<utility::string_t, utility::string_t>& value);

    /// <summary>
    /// If true, replace the field&#39;s existing metadata entirely; otherwise merge into it (optional, defaults to false). 
    /// </summary>
    bool isReplace() const;
    bool replaceIsSet() const;
    void unsetReplace();
    void setReplace(bool value);


protected:
    utility::string_t m_Path;
    bool m_PathIsSet;

    std::map<utility::string_t, utility::string_t> m_Metadata;
    bool m_MetadataIsSet;

    bool m_Replace;
    bool m_ReplaceIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateFieldMetadataEntry_H_ */
