/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "lance_namespace_rest_client/model/AddVirtualColumnOutputEntry.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

AddVirtualColumnOutputEntry::AddVirtualColumnOutputEntry()
{
    m_Column = utility::conversions::to_string_t("");
    m_ColumnIsSet = false;
    m_Struct_field = utility::conversions::to_string_t("");
    m_Struct_fieldIsSet = false;
    m_Data_typeIsSet = false;
    m_Nullable = false;
    m_NullableIsSet = false;
    m_MetadataIsSet = false;
}

AddVirtualColumnOutputEntry::~AddVirtualColumnOutputEntry()
{
}

void AddVirtualColumnOutputEntry::validate()
{
    // TODO: implement validation
}

web::json::value AddVirtualColumnOutputEntry::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ColumnIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("column"))] = ModelBase::toJson(m_Column);
    }
    if(m_Struct_fieldIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("struct_field"))] = ModelBase::toJson(m_Struct_field);
    }
    if(m_Data_typeIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("data_type"))] = ModelBase::toJson(m_Data_type);
    }
    if(m_NullableIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("nullable"))] = ModelBase::toJson(m_Nullable);
    }
    if(m_MetadataIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("metadata"))] = ModelBase::toJson(m_Metadata);
    }

    return val;
}

bool AddVirtualColumnOutputEntry::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("column"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("column")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setColumn;
            ok &= ModelBase::fromJson(fieldValue, refVal_setColumn);
            setColumn(refVal_setColumn);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("struct_field"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("struct_field")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStructField;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStructField);
            setStructField(refVal_setStructField);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data_type")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Object> refVal_setDataType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDataType);
            setDataType(refVal_setDataType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("nullable"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("nullable")));
        if(!fieldValue.is_null())
        {
            bool refVal_setNullable;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNullable);
            setNullable(refVal_setNullable);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("metadata"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("metadata")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, utility::string_t> refVal_setMetadata;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMetadata);
            setMetadata(refVal_setMetadata);
            
        }
    }
    return ok;
}

void AddVirtualColumnOutputEntry::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_ColumnIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("column")), m_Column));
    }
    if(m_Struct_fieldIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("struct_field")), m_Struct_field));
    }
    if(m_Data_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data_type")), m_Data_type));
    }
    if(m_NullableIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("nullable")), m_Nullable));
    }
    if(m_MetadataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("metadata")), m_Metadata));
    }
}

bool AddVirtualColumnOutputEntry::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("column"))))
    {
        utility::string_t refVal_setColumn;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("column"))), refVal_setColumn );
        setColumn(refVal_setColumn);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("struct_field"))))
    {
        utility::string_t refVal_setStructField;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("struct_field"))), refVal_setStructField );
        setStructField(refVal_setStructField);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data_type"))))
    {
        std::shared_ptr<Object> refVal_setDataType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data_type"))), refVal_setDataType );
        setDataType(refVal_setDataType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("nullable"))))
    {
        bool refVal_setNullable;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("nullable"))), refVal_setNullable );
        setNullable(refVal_setNullable);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("metadata"))))
    {
        std::map<utility::string_t, utility::string_t> refVal_setMetadata;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("metadata"))), refVal_setMetadata );
        setMetadata(refVal_setMetadata);
    }
    return ok;
}


utility::string_t AddVirtualColumnOutputEntry::getColumn() const
{
    return m_Column;
}


void AddVirtualColumnOutputEntry::setColumn(const utility::string_t& value)
{
    m_Column = value;
    m_ColumnIsSet = true;
}

bool AddVirtualColumnOutputEntry::columnIsSet() const
{
    return m_ColumnIsSet;
}

void AddVirtualColumnOutputEntry::unsetColumn()
{
    m_ColumnIsSet = false;
}
utility::string_t AddVirtualColumnOutputEntry::getStructField() const
{
    return m_Struct_field;
}


void AddVirtualColumnOutputEntry::setStructField(const utility::string_t& value)
{
    m_Struct_field = value;
    m_Struct_fieldIsSet = true;
}

bool AddVirtualColumnOutputEntry::structFieldIsSet() const
{
    return m_Struct_fieldIsSet;
}

void AddVirtualColumnOutputEntry::unsetStruct_field()
{
    m_Struct_fieldIsSet = false;
}
std::shared_ptr<Object> AddVirtualColumnOutputEntry::getDataType() const
{
    return m_Data_type;
}


void AddVirtualColumnOutputEntry::setDataType(const std::shared_ptr<Object>& value)
{
    m_Data_type = value;
    m_Data_typeIsSet = true;
}

bool AddVirtualColumnOutputEntry::dataTypeIsSet() const
{
    return m_Data_typeIsSet;
}

void AddVirtualColumnOutputEntry::unsetData_type()
{
    m_Data_typeIsSet = false;
}
bool AddVirtualColumnOutputEntry::isNullable() const
{
    return m_Nullable;
}

void AddVirtualColumnOutputEntry::setNullable(bool value)
{
    m_Nullable = value;
    m_NullableIsSet = true;
}

bool AddVirtualColumnOutputEntry::nullableIsSet() const
{
    return m_NullableIsSet;
}

void AddVirtualColumnOutputEntry::unsetNullable()
{
    m_NullableIsSet = false;
}
std::map<utility::string_t, utility::string_t> AddVirtualColumnOutputEntry::getMetadata() const
{
    return m_Metadata;
}


void AddVirtualColumnOutputEntry::setMetadata(const std::map<utility::string_t, utility::string_t>& value)
{
    m_Metadata = value;
    m_MetadataIsSet = true;
}

bool AddVirtualColumnOutputEntry::metadataIsSet() const
{
    return m_MetadataIsSet;
}

void AddVirtualColumnOutputEntry::unsetMetadata()
{
    m_MetadataIsSet = false;
}

}
}
}
}


