/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "lance_namespace_rest_client/model/AlterTransactionResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

AlterTransactionResponse::AlterTransactionResponse()
{
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
    m_PropertiesIsSet = false;
}

AlterTransactionResponse::~AlterTransactionResponse()
{
}

void AlterTransactionResponse::validate()
{
    // TODO: implement validation
}

web::json::value AlterTransactionResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StatusIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_PropertiesIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("properties"))] = ModelBase::toJson(m_Properties);
    }

    return val;
}

bool AlterTransactionResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("properties"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("properties")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, utility::string_t> refVal_setProperties;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProperties);
            setProperties(refVal_setProperties);
            
        }
    }
    return ok;
}

void AlterTransactionResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("status")), m_Status));
    }
    if(m_PropertiesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("properties")), m_Properties));
    }
}

bool AlterTransactionResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("properties"))))
    {
        std::map<utility::string_t, utility::string_t> refVal_setProperties;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("properties"))), refVal_setProperties );
        setProperties(refVal_setProperties);
    }
    return ok;
}


utility::string_t AlterTransactionResponse::getStatus() const
{
    return m_Status;
}


void AlterTransactionResponse::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool AlterTransactionResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void AlterTransactionResponse::unsetStatus()
{
    m_StatusIsSet = false;
}
std::map<utility::string_t, utility::string_t> AlterTransactionResponse::getProperties() const
{
    return m_Properties;
}


void AlterTransactionResponse::setProperties(const std::map<utility::string_t, utility::string_t>& value)
{
    m_Properties = value;
    m_PropertiesIsSet = true;
}

bool AlterTransactionResponse::propertiesIsSet() const
{
    return m_PropertiesIsSet;
}

void AlterTransactionResponse::unsetProperties()
{
    m_PropertiesIsSet = false;
}

}
}
}
}


