/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "LanceNamespace/model/AlterTableBackfillColumnsRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

AlterTableBackfillColumnsRequest::AlterTableBackfillColumnsRequest()
{
    m_IdentityIsSet = false;
    m_IdIsSet = false;
    m_Branch = utility::conversions::to_string_t("");
    m_BranchIsSet = false;
    m_Column = utility::conversions::to_string_t("");
    m_ColumnIsSet = false;
    m_Where = utility::conversions::to_string_t("");
    m_WhereIsSet = false;
    m_Concurrency = 0;
    m_ConcurrencyIsSet = false;
    m_Intra_applier_concurrency = 0;
    m_Intra_applier_concurrencyIsSet = false;
    m_Min_checkpoint_size = 0;
    m_Min_checkpoint_sizeIsSet = false;
    m_Max_checkpoint_size = 0;
    m_Max_checkpoint_sizeIsSet = false;
    m_Batch_checkpoint_flush_interval_seconds = 0.0;
    m_Batch_checkpoint_flush_interval_secondsIsSet = false;
    m_Read_version = 0;
    m_Read_versionIsSet = false;
    m_Task_size = 0;
    m_Task_sizeIsSet = false;
    m_Num_frags = 0;
    m_Num_fragsIsSet = false;
    m_Checkpoint_size = 0;
    m_Checkpoint_sizeIsSet = false;
    m_Commit_granularity = 0;
    m_Commit_granularityIsSet = false;
    m_Cluster = utility::conversions::to_string_t("");
    m_ClusterIsSet = false;
    m_Manifest = utility::conversions::to_string_t("");
    m_ManifestIsSet = false;
}

AlterTableBackfillColumnsRequest::~AlterTableBackfillColumnsRequest()
{
}

void AlterTableBackfillColumnsRequest::validate()
{
    // TODO: implement validation
}

web::json::value AlterTableBackfillColumnsRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdentityIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("identity"))] = ModelBase::toJson(m_Identity);
    }
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_BranchIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("branch"))] = ModelBase::toJson(m_Branch);
    }
    if(m_ColumnIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("column"))] = ModelBase::toJson(m_Column);
    }
    if(m_WhereIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("where"))] = ModelBase::toJson(m_Where);
    }
    if(m_ConcurrencyIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("concurrency"))] = ModelBase::toJson(m_Concurrency);
    }
    if(m_Intra_applier_concurrencyIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("intra_applier_concurrency"))] = ModelBase::toJson(m_Intra_applier_concurrency);
    }
    if(m_Min_checkpoint_sizeIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("min_checkpoint_size"))] = ModelBase::toJson(m_Min_checkpoint_size);
    }
    if(m_Max_checkpoint_sizeIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("max_checkpoint_size"))] = ModelBase::toJson(m_Max_checkpoint_size);
    }
    if(m_Batch_checkpoint_flush_interval_secondsIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("batch_checkpoint_flush_interval_seconds"))] = ModelBase::toJson(m_Batch_checkpoint_flush_interval_seconds);
    }
    if(m_Read_versionIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("read_version"))] = ModelBase::toJson(m_Read_version);
    }
    if(m_Task_sizeIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("task_size"))] = ModelBase::toJson(m_Task_size);
    }
    if(m_Num_fragsIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("num_frags"))] = ModelBase::toJson(m_Num_frags);
    }
    if(m_Checkpoint_sizeIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("checkpoint_size"))] = ModelBase::toJson(m_Checkpoint_size);
    }
    if(m_Commit_granularityIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("commit_granularity"))] = ModelBase::toJson(m_Commit_granularity);
    }
    if(m_ClusterIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("cluster"))] = ModelBase::toJson(m_Cluster);
    }
    if(m_ManifestIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("manifest"))] = ModelBase::toJson(m_Manifest);
    }

    return val;
}

bool AlterTableBackfillColumnsRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("identity"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("identity")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Identity> refVal_setIdentity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIdentity);
            setIdentity(refVal_setIdentity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("branch"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("branch")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBranch;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBranch);
            setBranch(refVal_setBranch);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("column"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("column")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setColumn;
            ok &= ModelBase::fromJson(fieldValue, refVal_setColumn);
            setColumn(refVal_setColumn);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("where"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("where")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWhere;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWhere);
            setWhere(refVal_setWhere);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("concurrency"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("concurrency")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setConcurrency;
            ok &= ModelBase::fromJson(fieldValue, refVal_setConcurrency);
            setConcurrency(refVal_setConcurrency);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("intra_applier_concurrency"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("intra_applier_concurrency")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setIntraApplierConcurrency;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIntraApplierConcurrency);
            setIntraApplierConcurrency(refVal_setIntraApplierConcurrency);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("min_checkpoint_size"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("min_checkpoint_size")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setMinCheckpointSize;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMinCheckpointSize);
            setMinCheckpointSize(refVal_setMinCheckpointSize);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("max_checkpoint_size"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("max_checkpoint_size")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setMaxCheckpointSize;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMaxCheckpointSize);
            setMaxCheckpointSize(refVal_setMaxCheckpointSize);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("batch_checkpoint_flush_interval_seconds"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("batch_checkpoint_flush_interval_seconds")));
        if(!fieldValue.is_null())
        {
            double refVal_setBatchCheckpointFlushIntervalSeconds;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBatchCheckpointFlushIntervalSeconds);
            setBatchCheckpointFlushIntervalSeconds(refVal_setBatchCheckpointFlushIntervalSeconds);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("read_version"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("read_version")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setReadVersion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReadVersion);
            setReadVersion(refVal_setReadVersion);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("task_size"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("task_size")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTaskSize;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTaskSize);
            setTaskSize(refVal_setTaskSize);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("num_frags"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("num_frags")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setNumFrags;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNumFrags);
            setNumFrags(refVal_setNumFrags);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("checkpoint_size"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("checkpoint_size")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setCheckpointSize;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCheckpointSize);
            setCheckpointSize(refVal_setCheckpointSize);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("commit_granularity"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("commit_granularity")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setCommitGranularity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCommitGranularity);
            setCommitGranularity(refVal_setCommitGranularity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("cluster"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("cluster")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCluster;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCluster);
            setCluster(refVal_setCluster);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("manifest"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("manifest")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setManifest;
            ok &= ModelBase::fromJson(fieldValue, refVal_setManifest);
            setManifest(refVal_setManifest);
            
        }
    }
    return ok;
}

void AlterTableBackfillColumnsRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdentityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("identity")), m_Identity));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_BranchIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("branch")), m_Branch));
    }
    if(m_ColumnIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("column")), m_Column));
    }
    if(m_WhereIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("where")), m_Where));
    }
    if(m_ConcurrencyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("concurrency")), m_Concurrency));
    }
    if(m_Intra_applier_concurrencyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("intra_applier_concurrency")), m_Intra_applier_concurrency));
    }
    if(m_Min_checkpoint_sizeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("min_checkpoint_size")), m_Min_checkpoint_size));
    }
    if(m_Max_checkpoint_sizeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("max_checkpoint_size")), m_Max_checkpoint_size));
    }
    if(m_Batch_checkpoint_flush_interval_secondsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("batch_checkpoint_flush_interval_seconds")), m_Batch_checkpoint_flush_interval_seconds));
    }
    if(m_Read_versionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("read_version")), m_Read_version));
    }
    if(m_Task_sizeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("task_size")), m_Task_size));
    }
    if(m_Num_fragsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("num_frags")), m_Num_frags));
    }
    if(m_Checkpoint_sizeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("checkpoint_size")), m_Checkpoint_size));
    }
    if(m_Commit_granularityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("commit_granularity")), m_Commit_granularity));
    }
    if(m_ClusterIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("cluster")), m_Cluster));
    }
    if(m_ManifestIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("manifest")), m_Manifest));
    }
}

bool AlterTableBackfillColumnsRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("identity"))))
    {
        std::shared_ptr<Identity> refVal_setIdentity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("identity"))), refVal_setIdentity );
        setIdentity(refVal_setIdentity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        std::vector<utility::string_t> refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("branch"))))
    {
        utility::string_t refVal_setBranch;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("branch"))), refVal_setBranch );
        setBranch(refVal_setBranch);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("column"))))
    {
        utility::string_t refVal_setColumn;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("column"))), refVal_setColumn );
        setColumn(refVal_setColumn);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("where"))))
    {
        utility::string_t refVal_setWhere;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("where"))), refVal_setWhere );
        setWhere(refVal_setWhere);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("concurrency"))))
    {
        int32_t refVal_setConcurrency;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("concurrency"))), refVal_setConcurrency );
        setConcurrency(refVal_setConcurrency);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("intra_applier_concurrency"))))
    {
        int32_t refVal_setIntraApplierConcurrency;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("intra_applier_concurrency"))), refVal_setIntraApplierConcurrency );
        setIntraApplierConcurrency(refVal_setIntraApplierConcurrency);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("min_checkpoint_size"))))
    {
        int32_t refVal_setMinCheckpointSize;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("min_checkpoint_size"))), refVal_setMinCheckpointSize );
        setMinCheckpointSize(refVal_setMinCheckpointSize);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("max_checkpoint_size"))))
    {
        int32_t refVal_setMaxCheckpointSize;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("max_checkpoint_size"))), refVal_setMaxCheckpointSize );
        setMaxCheckpointSize(refVal_setMaxCheckpointSize);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("batch_checkpoint_flush_interval_seconds"))))
    {
        double refVal_setBatchCheckpointFlushIntervalSeconds;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("batch_checkpoint_flush_interval_seconds"))), refVal_setBatchCheckpointFlushIntervalSeconds );
        setBatchCheckpointFlushIntervalSeconds(refVal_setBatchCheckpointFlushIntervalSeconds);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("read_version"))))
    {
        int32_t refVal_setReadVersion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("read_version"))), refVal_setReadVersion );
        setReadVersion(refVal_setReadVersion);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("task_size"))))
    {
        int32_t refVal_setTaskSize;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("task_size"))), refVal_setTaskSize );
        setTaskSize(refVal_setTaskSize);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("num_frags"))))
    {
        int32_t refVal_setNumFrags;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("num_frags"))), refVal_setNumFrags );
        setNumFrags(refVal_setNumFrags);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("checkpoint_size"))))
    {
        int32_t refVal_setCheckpointSize;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("checkpoint_size"))), refVal_setCheckpointSize );
        setCheckpointSize(refVal_setCheckpointSize);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("commit_granularity"))))
    {
        int32_t refVal_setCommitGranularity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("commit_granularity"))), refVal_setCommitGranularity );
        setCommitGranularity(refVal_setCommitGranularity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("cluster"))))
    {
        utility::string_t refVal_setCluster;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("cluster"))), refVal_setCluster );
        setCluster(refVal_setCluster);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("manifest"))))
    {
        utility::string_t refVal_setManifest;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("manifest"))), refVal_setManifest );
        setManifest(refVal_setManifest);
    }
    return ok;
}


std::shared_ptr<Identity> AlterTableBackfillColumnsRequest::getIdentity() const
{
    return m_Identity;
}


void AlterTableBackfillColumnsRequest::setIdentity(const std::shared_ptr<Identity>& value)
{
    m_Identity = value;
    m_IdentityIsSet = true;
}

bool AlterTableBackfillColumnsRequest::identityIsSet() const
{
    return m_IdentityIsSet;
}

void AlterTableBackfillColumnsRequest::unsetIdentity()
{
    m_IdentityIsSet = false;
}
std::vector<utility::string_t> AlterTableBackfillColumnsRequest::getId() const
{
    return m_Id;
}


void AlterTableBackfillColumnsRequest::setId(const std::vector<utility::string_t>& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool AlterTableBackfillColumnsRequest::idIsSet() const
{
    return m_IdIsSet;
}

void AlterTableBackfillColumnsRequest::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t AlterTableBackfillColumnsRequest::getBranch() const
{
    return m_Branch;
}


void AlterTableBackfillColumnsRequest::setBranch(const utility::string_t& value)
{
    m_Branch = value;
    m_BranchIsSet = true;
}

bool AlterTableBackfillColumnsRequest::branchIsSet() const
{
    return m_BranchIsSet;
}

void AlterTableBackfillColumnsRequest::unsetBranch()
{
    m_BranchIsSet = false;
}
utility::string_t AlterTableBackfillColumnsRequest::getColumn() const
{
    return m_Column;
}


void AlterTableBackfillColumnsRequest::setColumn(const utility::string_t& value)
{
    m_Column = value;
    m_ColumnIsSet = true;
}

bool AlterTableBackfillColumnsRequest::columnIsSet() const
{
    return m_ColumnIsSet;
}

void AlterTableBackfillColumnsRequest::unsetColumn()
{
    m_ColumnIsSet = false;
}
utility::string_t AlterTableBackfillColumnsRequest::getWhere() const
{
    return m_Where;
}


void AlterTableBackfillColumnsRequest::setWhere(const utility::string_t& value)
{
    m_Where = value;
    m_WhereIsSet = true;
}

bool AlterTableBackfillColumnsRequest::whereIsSet() const
{
    return m_WhereIsSet;
}

void AlterTableBackfillColumnsRequest::unsetWhere()
{
    m_WhereIsSet = false;
}
int32_t AlterTableBackfillColumnsRequest::getConcurrency() const
{
    return m_Concurrency;
}

void AlterTableBackfillColumnsRequest::setConcurrency(int32_t value)
{
    m_Concurrency = value;
    m_ConcurrencyIsSet = true;
}

bool AlterTableBackfillColumnsRequest::concurrencyIsSet() const
{
    return m_ConcurrencyIsSet;
}

void AlterTableBackfillColumnsRequest::unsetConcurrency()
{
    m_ConcurrencyIsSet = false;
}
int32_t AlterTableBackfillColumnsRequest::getIntraApplierConcurrency() const
{
    return m_Intra_applier_concurrency;
}

void AlterTableBackfillColumnsRequest::setIntraApplierConcurrency(int32_t value)
{
    m_Intra_applier_concurrency = value;
    m_Intra_applier_concurrencyIsSet = true;
}

bool AlterTableBackfillColumnsRequest::intraApplierConcurrencyIsSet() const
{
    return m_Intra_applier_concurrencyIsSet;
}

void AlterTableBackfillColumnsRequest::unsetIntra_applier_concurrency()
{
    m_Intra_applier_concurrencyIsSet = false;
}
int32_t AlterTableBackfillColumnsRequest::getMinCheckpointSize() const
{
    return m_Min_checkpoint_size;
}

void AlterTableBackfillColumnsRequest::setMinCheckpointSize(int32_t value)
{
    m_Min_checkpoint_size = value;
    m_Min_checkpoint_sizeIsSet = true;
}

bool AlterTableBackfillColumnsRequest::minCheckpointSizeIsSet() const
{
    return m_Min_checkpoint_sizeIsSet;
}

void AlterTableBackfillColumnsRequest::unsetMin_checkpoint_size()
{
    m_Min_checkpoint_sizeIsSet = false;
}
int32_t AlterTableBackfillColumnsRequest::getMaxCheckpointSize() const
{
    return m_Max_checkpoint_size;
}

void AlterTableBackfillColumnsRequest::setMaxCheckpointSize(int32_t value)
{
    m_Max_checkpoint_size = value;
    m_Max_checkpoint_sizeIsSet = true;
}

bool AlterTableBackfillColumnsRequest::maxCheckpointSizeIsSet() const
{
    return m_Max_checkpoint_sizeIsSet;
}

void AlterTableBackfillColumnsRequest::unsetMax_checkpoint_size()
{
    m_Max_checkpoint_sizeIsSet = false;
}
double AlterTableBackfillColumnsRequest::getBatchCheckpointFlushIntervalSeconds() const
{
    return m_Batch_checkpoint_flush_interval_seconds;
}

void AlterTableBackfillColumnsRequest::setBatchCheckpointFlushIntervalSeconds(double value)
{
    m_Batch_checkpoint_flush_interval_seconds = value;
    m_Batch_checkpoint_flush_interval_secondsIsSet = true;
}

bool AlterTableBackfillColumnsRequest::batchCheckpointFlushIntervalSecondsIsSet() const
{
    return m_Batch_checkpoint_flush_interval_secondsIsSet;
}

void AlterTableBackfillColumnsRequest::unsetBatch_checkpoint_flush_interval_seconds()
{
    m_Batch_checkpoint_flush_interval_secondsIsSet = false;
}
int32_t AlterTableBackfillColumnsRequest::getReadVersion() const
{
    return m_Read_version;
}

void AlterTableBackfillColumnsRequest::setReadVersion(int32_t value)
{
    m_Read_version = value;
    m_Read_versionIsSet = true;
}

bool AlterTableBackfillColumnsRequest::readVersionIsSet() const
{
    return m_Read_versionIsSet;
}

void AlterTableBackfillColumnsRequest::unsetRead_version()
{
    m_Read_versionIsSet = false;
}
int32_t AlterTableBackfillColumnsRequest::getTaskSize() const
{
    return m_Task_size;
}

void AlterTableBackfillColumnsRequest::setTaskSize(int32_t value)
{
    m_Task_size = value;
    m_Task_sizeIsSet = true;
}

bool AlterTableBackfillColumnsRequest::taskSizeIsSet() const
{
    return m_Task_sizeIsSet;
}

void AlterTableBackfillColumnsRequest::unsetTask_size()
{
    m_Task_sizeIsSet = false;
}
int32_t AlterTableBackfillColumnsRequest::getNumFrags() const
{
    return m_Num_frags;
}

void AlterTableBackfillColumnsRequest::setNumFrags(int32_t value)
{
    m_Num_frags = value;
    m_Num_fragsIsSet = true;
}

bool AlterTableBackfillColumnsRequest::numFragsIsSet() const
{
    return m_Num_fragsIsSet;
}

void AlterTableBackfillColumnsRequest::unsetNum_frags()
{
    m_Num_fragsIsSet = false;
}
int32_t AlterTableBackfillColumnsRequest::getCheckpointSize() const
{
    return m_Checkpoint_size;
}

void AlterTableBackfillColumnsRequest::setCheckpointSize(int32_t value)
{
    m_Checkpoint_size = value;
    m_Checkpoint_sizeIsSet = true;
}

bool AlterTableBackfillColumnsRequest::checkpointSizeIsSet() const
{
    return m_Checkpoint_sizeIsSet;
}

void AlterTableBackfillColumnsRequest::unsetCheckpoint_size()
{
    m_Checkpoint_sizeIsSet = false;
}
int32_t AlterTableBackfillColumnsRequest::getCommitGranularity() const
{
    return m_Commit_granularity;
}

void AlterTableBackfillColumnsRequest::setCommitGranularity(int32_t value)
{
    m_Commit_granularity = value;
    m_Commit_granularityIsSet = true;
}

bool AlterTableBackfillColumnsRequest::commitGranularityIsSet() const
{
    return m_Commit_granularityIsSet;
}

void AlterTableBackfillColumnsRequest::unsetCommit_granularity()
{
    m_Commit_granularityIsSet = false;
}
utility::string_t AlterTableBackfillColumnsRequest::getCluster() const
{
    return m_Cluster;
}


void AlterTableBackfillColumnsRequest::setCluster(const utility::string_t& value)
{
    m_Cluster = value;
    m_ClusterIsSet = true;
}

bool AlterTableBackfillColumnsRequest::clusterIsSet() const
{
    return m_ClusterIsSet;
}

void AlterTableBackfillColumnsRequest::unsetCluster()
{
    m_ClusterIsSet = false;
}
utility::string_t AlterTableBackfillColumnsRequest::getManifest() const
{
    return m_Manifest;
}


void AlterTableBackfillColumnsRequest::setManifest(const utility::string_t& value)
{
    m_Manifest = value;
    m_ManifestIsSet = true;
}

bool AlterTableBackfillColumnsRequest::manifestIsSet() const
{
    return m_ManifestIsSet;
}

void AlterTableBackfillColumnsRequest::unsetManifest()
{
    m_ManifestIsSet = false;
}

}
}
}
}


