/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "lance_namespace_rest_client/model/CreateTableIndexRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CreateTableIndexRequest::CreateTableIndexRequest()
{
    m_IdentityIsSet = false;
    m_ContextIsSet = false;
    m_IdIsSet = false;
    m_Branch = utility::conversions::to_string_t("");
    m_BranchIsSet = false;
    m_Column = utility::conversions::to_string_t("");
    m_ColumnIsSet = false;
    m_Index_type = utility::conversions::to_string_t("");
    m_Index_typeIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Distance_type = utility::conversions::to_string_t("");
    m_Distance_typeIsSet = false;
    m_With_position = false;
    m_With_positionIsSet = false;
    m_Base_tokenizer = utility::conversions::to_string_t("");
    m_Base_tokenizerIsSet = false;
    m_Language = utility::conversions::to_string_t("");
    m_LanguageIsSet = false;
    m_Max_token_length = 0;
    m_Max_token_lengthIsSet = false;
    m_Lower_case = false;
    m_Lower_caseIsSet = false;
    m_Stem = false;
    m_StemIsSet = false;
    m_Remove_stop_words = false;
    m_Remove_stop_wordsIsSet = false;
    m_Ascii_folding = false;
    m_Ascii_foldingIsSet = false;
}

CreateTableIndexRequest::~CreateTableIndexRequest()
{
}

void CreateTableIndexRequest::validate()
{
    // TODO: implement validation
}

web::json::value CreateTableIndexRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdentityIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("identity"))] = ModelBase::toJson(m_Identity);
    }
    if(m_ContextIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("context"))] = ModelBase::toJson(m_Context);
    }
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_BranchIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("branch"))] = ModelBase::toJson(m_Branch);
    }
    if(m_ColumnIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("column"))] = ModelBase::toJson(m_Column);
    }
    if(m_Index_typeIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("index_type"))] = ModelBase::toJson(m_Index_type);
    }
    if(m_NameIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_Distance_typeIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("distance_type"))] = ModelBase::toJson(m_Distance_type);
    }
    if(m_With_positionIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("with_position"))] = ModelBase::toJson(m_With_position);
    }
    if(m_Base_tokenizerIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("base_tokenizer"))] = ModelBase::toJson(m_Base_tokenizer);
    }
    if(m_LanguageIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("language"))] = ModelBase::toJson(m_Language);
    }
    if(m_Max_token_lengthIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("max_token_length"))] = ModelBase::toJson(m_Max_token_length);
    }
    if(m_Lower_caseIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("lower_case"))] = ModelBase::toJson(m_Lower_case);
    }
    if(m_StemIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("stem"))] = ModelBase::toJson(m_Stem);
    }
    if(m_Remove_stop_wordsIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("remove_stop_words"))] = ModelBase::toJson(m_Remove_stop_words);
    }
    if(m_Ascii_foldingIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("ascii_folding"))] = ModelBase::toJson(m_Ascii_folding);
    }

    return val;
}

bool CreateTableIndexRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("identity"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("identity")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Identity> refVal_setIdentity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIdentity);
            setIdentity(refVal_setIdentity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("context"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("context")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, utility::string_t> refVal_setContext;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContext);
            setContext(refVal_setContext);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("branch"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("branch")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBranch;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBranch);
            setBranch(refVal_setBranch);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("column"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("column")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setColumn;
            ok &= ModelBase::fromJson(fieldValue, refVal_setColumn);
            setColumn(refVal_setColumn);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("index_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("index_type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIndexType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIndexType);
            setIndexType(refVal_setIndexType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("distance_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("distance_type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDistanceType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDistanceType);
            setDistanceType(refVal_setDistanceType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("with_position"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("with_position")));
        if(!fieldValue.is_null())
        {
            bool refVal_setWithPosition;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWithPosition);
            setWithPosition(refVal_setWithPosition);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("base_tokenizer"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("base_tokenizer")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBaseTokenizer;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBaseTokenizer);
            setBaseTokenizer(refVal_setBaseTokenizer);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("language"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("language")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLanguage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLanguage);
            setLanguage(refVal_setLanguage);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("max_token_length"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("max_token_length")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setMaxTokenLength;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMaxTokenLength);
            setMaxTokenLength(refVal_setMaxTokenLength);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("lower_case"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("lower_case")));
        if(!fieldValue.is_null())
        {
            bool refVal_setLowerCase;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLowerCase);
            setLowerCase(refVal_setLowerCase);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("stem"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("stem")));
        if(!fieldValue.is_null())
        {
            bool refVal_setStem;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStem);
            setStem(refVal_setStem);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("remove_stop_words"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("remove_stop_words")));
        if(!fieldValue.is_null())
        {
            bool refVal_setRemoveStopWords;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRemoveStopWords);
            setRemoveStopWords(refVal_setRemoveStopWords);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("ascii_folding"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("ascii_folding")));
        if(!fieldValue.is_null())
        {
            bool refVal_setAsciiFolding;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAsciiFolding);
            setAsciiFolding(refVal_setAsciiFolding);
            
        }
    }
    return ok;
}

void CreateTableIndexRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdentityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("identity")), m_Identity));
    }
    if(m_ContextIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("context")), m_Context));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_BranchIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("branch")), m_Branch));
    }
    if(m_ColumnIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("column")), m_Column));
    }
    if(m_Index_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("index_type")), m_Index_type));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_Distance_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("distance_type")), m_Distance_type));
    }
    if(m_With_positionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("with_position")), m_With_position));
    }
    if(m_Base_tokenizerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("base_tokenizer")), m_Base_tokenizer));
    }
    if(m_LanguageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("language")), m_Language));
    }
    if(m_Max_token_lengthIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("max_token_length")), m_Max_token_length));
    }
    if(m_Lower_caseIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("lower_case")), m_Lower_case));
    }
    if(m_StemIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("stem")), m_Stem));
    }
    if(m_Remove_stop_wordsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("remove_stop_words")), m_Remove_stop_words));
    }
    if(m_Ascii_foldingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("ascii_folding")), m_Ascii_folding));
    }
}

bool CreateTableIndexRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("identity"))))
    {
        std::shared_ptr<Identity> refVal_setIdentity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("identity"))), refVal_setIdentity );
        setIdentity(refVal_setIdentity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("context"))))
    {
        std::map<utility::string_t, utility::string_t> refVal_setContext;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("context"))), refVal_setContext );
        setContext(refVal_setContext);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        std::vector<utility::string_t> refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("branch"))))
    {
        utility::string_t refVal_setBranch;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("branch"))), refVal_setBranch );
        setBranch(refVal_setBranch);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("column"))))
    {
        utility::string_t refVal_setColumn;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("column"))), refVal_setColumn );
        setColumn(refVal_setColumn);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("index_type"))))
    {
        utility::string_t refVal_setIndexType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("index_type"))), refVal_setIndexType );
        setIndexType(refVal_setIndexType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("distance_type"))))
    {
        utility::string_t refVal_setDistanceType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("distance_type"))), refVal_setDistanceType );
        setDistanceType(refVal_setDistanceType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("with_position"))))
    {
        bool refVal_setWithPosition;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("with_position"))), refVal_setWithPosition );
        setWithPosition(refVal_setWithPosition);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("base_tokenizer"))))
    {
        utility::string_t refVal_setBaseTokenizer;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("base_tokenizer"))), refVal_setBaseTokenizer );
        setBaseTokenizer(refVal_setBaseTokenizer);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("language"))))
    {
        utility::string_t refVal_setLanguage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("language"))), refVal_setLanguage );
        setLanguage(refVal_setLanguage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("max_token_length"))))
    {
        int32_t refVal_setMaxTokenLength;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("max_token_length"))), refVal_setMaxTokenLength );
        setMaxTokenLength(refVal_setMaxTokenLength);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("lower_case"))))
    {
        bool refVal_setLowerCase;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("lower_case"))), refVal_setLowerCase );
        setLowerCase(refVal_setLowerCase);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("stem"))))
    {
        bool refVal_setStem;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("stem"))), refVal_setStem );
        setStem(refVal_setStem);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("remove_stop_words"))))
    {
        bool refVal_setRemoveStopWords;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("remove_stop_words"))), refVal_setRemoveStopWords );
        setRemoveStopWords(refVal_setRemoveStopWords);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("ascii_folding"))))
    {
        bool refVal_setAsciiFolding;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("ascii_folding"))), refVal_setAsciiFolding );
        setAsciiFolding(refVal_setAsciiFolding);
    }
    return ok;
}


std::shared_ptr<Identity> CreateTableIndexRequest::getIdentity() const
{
    return m_Identity;
}


void CreateTableIndexRequest::setIdentity(const std::shared_ptr<Identity>& value)
{
    m_Identity = value;
    m_IdentityIsSet = true;
}

bool CreateTableIndexRequest::identityIsSet() const
{
    return m_IdentityIsSet;
}

void CreateTableIndexRequest::unsetIdentity()
{
    m_IdentityIsSet = false;
}
std::map<utility::string_t, utility::string_t> CreateTableIndexRequest::getContext() const
{
    return m_Context;
}


void CreateTableIndexRequest::setContext(const std::map<utility::string_t, utility::string_t>& value)
{
    m_Context = value;
    m_ContextIsSet = true;
}

bool CreateTableIndexRequest::contextIsSet() const
{
    return m_ContextIsSet;
}

void CreateTableIndexRequest::unsetContext()
{
    m_ContextIsSet = false;
}
std::vector<utility::string_t> CreateTableIndexRequest::getId() const
{
    return m_Id;
}


void CreateTableIndexRequest::setId(const std::vector<utility::string_t>& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool CreateTableIndexRequest::idIsSet() const
{
    return m_IdIsSet;
}

void CreateTableIndexRequest::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t CreateTableIndexRequest::getBranch() const
{
    return m_Branch;
}


void CreateTableIndexRequest::setBranch(const utility::string_t& value)
{
    m_Branch = value;
    m_BranchIsSet = true;
}

bool CreateTableIndexRequest::branchIsSet() const
{
    return m_BranchIsSet;
}

void CreateTableIndexRequest::unsetBranch()
{
    m_BranchIsSet = false;
}
utility::string_t CreateTableIndexRequest::getColumn() const
{
    return m_Column;
}


void CreateTableIndexRequest::setColumn(const utility::string_t& value)
{
    m_Column = value;
    m_ColumnIsSet = true;
}

bool CreateTableIndexRequest::columnIsSet() const
{
    return m_ColumnIsSet;
}

void CreateTableIndexRequest::unsetColumn()
{
    m_ColumnIsSet = false;
}
utility::string_t CreateTableIndexRequest::getIndexType() const
{
    return m_Index_type;
}


void CreateTableIndexRequest::setIndexType(const utility::string_t& value)
{
    m_Index_type = value;
    m_Index_typeIsSet = true;
}

bool CreateTableIndexRequest::indexTypeIsSet() const
{
    return m_Index_typeIsSet;
}

void CreateTableIndexRequest::unsetIndex_type()
{
    m_Index_typeIsSet = false;
}
utility::string_t CreateTableIndexRequest::getName() const
{
    return m_Name;
}


void CreateTableIndexRequest::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool CreateTableIndexRequest::nameIsSet() const
{
    return m_NameIsSet;
}

void CreateTableIndexRequest::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t CreateTableIndexRequest::getDistanceType() const
{
    return m_Distance_type;
}


void CreateTableIndexRequest::setDistanceType(const utility::string_t& value)
{
    m_Distance_type = value;
    m_Distance_typeIsSet = true;
}

bool CreateTableIndexRequest::distanceTypeIsSet() const
{
    return m_Distance_typeIsSet;
}

void CreateTableIndexRequest::unsetDistance_type()
{
    m_Distance_typeIsSet = false;
}
bool CreateTableIndexRequest::isWithPosition() const
{
    return m_With_position;
}

void CreateTableIndexRequest::setWithPosition(bool value)
{
    m_With_position = value;
    m_With_positionIsSet = true;
}

bool CreateTableIndexRequest::withPositionIsSet() const
{
    return m_With_positionIsSet;
}

void CreateTableIndexRequest::unsetWith_position()
{
    m_With_positionIsSet = false;
}
utility::string_t CreateTableIndexRequest::getBaseTokenizer() const
{
    return m_Base_tokenizer;
}


void CreateTableIndexRequest::setBaseTokenizer(const utility::string_t& value)
{
    m_Base_tokenizer = value;
    m_Base_tokenizerIsSet = true;
}

bool CreateTableIndexRequest::baseTokenizerIsSet() const
{
    return m_Base_tokenizerIsSet;
}

void CreateTableIndexRequest::unsetBase_tokenizer()
{
    m_Base_tokenizerIsSet = false;
}
utility::string_t CreateTableIndexRequest::getLanguage() const
{
    return m_Language;
}


void CreateTableIndexRequest::setLanguage(const utility::string_t& value)
{
    m_Language = value;
    m_LanguageIsSet = true;
}

bool CreateTableIndexRequest::languageIsSet() const
{
    return m_LanguageIsSet;
}

void CreateTableIndexRequest::unsetLanguage()
{
    m_LanguageIsSet = false;
}
int32_t CreateTableIndexRequest::getMaxTokenLength() const
{
    return m_Max_token_length;
}

void CreateTableIndexRequest::setMaxTokenLength(int32_t value)
{
    m_Max_token_length = value;
    m_Max_token_lengthIsSet = true;
}

bool CreateTableIndexRequest::maxTokenLengthIsSet() const
{
    return m_Max_token_lengthIsSet;
}

void CreateTableIndexRequest::unsetMax_token_length()
{
    m_Max_token_lengthIsSet = false;
}
bool CreateTableIndexRequest::isLowerCase() const
{
    return m_Lower_case;
}

void CreateTableIndexRequest::setLowerCase(bool value)
{
    m_Lower_case = value;
    m_Lower_caseIsSet = true;
}

bool CreateTableIndexRequest::lowerCaseIsSet() const
{
    return m_Lower_caseIsSet;
}

void CreateTableIndexRequest::unsetLower_case()
{
    m_Lower_caseIsSet = false;
}
bool CreateTableIndexRequest::isStem() const
{
    return m_Stem;
}

void CreateTableIndexRequest::setStem(bool value)
{
    m_Stem = value;
    m_StemIsSet = true;
}

bool CreateTableIndexRequest::stemIsSet() const
{
    return m_StemIsSet;
}

void CreateTableIndexRequest::unsetStem()
{
    m_StemIsSet = false;
}
bool CreateTableIndexRequest::isRemoveStopWords() const
{
    return m_Remove_stop_words;
}

void CreateTableIndexRequest::setRemoveStopWords(bool value)
{
    m_Remove_stop_words = value;
    m_Remove_stop_wordsIsSet = true;
}

bool CreateTableIndexRequest::removeStopWordsIsSet() const
{
    return m_Remove_stop_wordsIsSet;
}

void CreateTableIndexRequest::unsetRemove_stop_words()
{
    m_Remove_stop_wordsIsSet = false;
}
bool CreateTableIndexRequest::isAsciiFolding() const
{
    return m_Ascii_folding;
}

void CreateTableIndexRequest::setAsciiFolding(bool value)
{
    m_Ascii_folding = value;
    m_Ascii_foldingIsSet = true;
}

bool CreateTableIndexRequest::asciiFoldingIsSet() const
{
    return m_Ascii_foldingIsSet;
}

void CreateTableIndexRequest::unsetAscii_folding()
{
    m_Ascii_foldingIsSet = false;
}

}
}
}
}


