/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "lance_namespace_rest_client/model/JsonArrowSchema.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

JsonArrowSchema::JsonArrowSchema()
{
    m_FieldsIsSet = false;
    m_MetadataIsSet = false;
}

JsonArrowSchema::~JsonArrowSchema()
{
}

void JsonArrowSchema::validate()
{
    // TODO: implement validation
}

web::json::value JsonArrowSchema::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_FieldsIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("fields"))] = ModelBase::toJson(m_Fields);
    }
    if(m_MetadataIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("metadata"))] = ModelBase::toJson(m_Metadata);
    }

    return val;
}

bool JsonArrowSchema::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("fields"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("fields")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<JsonArrowField>> refVal_setFields;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFields);
            setFields(refVal_setFields);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("metadata"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("metadata")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, utility::string_t> refVal_setMetadata;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMetadata);
            setMetadata(refVal_setMetadata);
            
        }
    }
    return ok;
}

void JsonArrowSchema::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_FieldsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("fields")), m_Fields));
    }
    if(m_MetadataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("metadata")), m_Metadata));
    }
}

bool JsonArrowSchema::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("fields"))))
    {
        std::vector<std::shared_ptr<JsonArrowField>> refVal_setFields;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("fields"))), refVal_setFields );
        setFields(refVal_setFields);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("metadata"))))
    {
        std::map<utility::string_t, utility::string_t> refVal_setMetadata;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("metadata"))), refVal_setMetadata );
        setMetadata(refVal_setMetadata);
    }
    return ok;
}


std::vector<std::shared_ptr<JsonArrowField>> JsonArrowSchema::getFields() const
{
    return m_Fields;
}


void JsonArrowSchema::setFields(const std::vector<std::shared_ptr<JsonArrowField>>& value)
{
    m_Fields = value;
    m_FieldsIsSet = true;
}

bool JsonArrowSchema::fieldsIsSet() const
{
    return m_FieldsIsSet;
}

void JsonArrowSchema::unsetFields()
{
    m_FieldsIsSet = false;
}
std::map<utility::string_t, utility::string_t> JsonArrowSchema::getMetadata() const
{
    return m_Metadata;
}


void JsonArrowSchema::setMetadata(const std::map<utility::string_t, utility::string_t>& value)
{
    m_Metadata = value;
    m_MetadataIsSet = true;
}

bool JsonArrowSchema::metadataIsSet() const
{
    return m_MetadataIsSet;
}

void JsonArrowSchema::unsetMetadata()
{
    m_MetadataIsSet = false;
}

}
}
}
}


