/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "lance_namespace_rest_client/model/ListTablesRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ListTablesRequest::ListTablesRequest()
{
    m_IdentityIsSet = false;
    m_ContextIsSet = false;
    m_IdIsSet = false;
    m_Page_token = utility::conversions::to_string_t("");
    m_Page_tokenIsSet = false;
    m_Limit = 0;
    m_LimitIsSet = false;
    m_Include_declared = false;
    m_Include_declaredIsSet = false;
}

ListTablesRequest::~ListTablesRequest()
{
}

void ListTablesRequest::validate()
{
    // TODO: implement validation
}

web::json::value ListTablesRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdentityIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("identity"))] = ModelBase::toJson(m_Identity);
    }
    if(m_ContextIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("context"))] = ModelBase::toJson(m_Context);
    }
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Page_tokenIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("page_token"))] = ModelBase::toJson(m_Page_token);
    }
    if(m_LimitIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("limit"))] = ModelBase::toJson(m_Limit);
    }
    if(m_Include_declaredIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("include_declared"))] = ModelBase::toJson(m_Include_declared);
    }

    return val;
}

bool ListTablesRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("identity"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("identity")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Identity> refVal_setIdentity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIdentity);
            setIdentity(refVal_setIdentity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("context"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("context")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, utility::string_t> refVal_setContext;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContext);
            setContext(refVal_setContext);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("page_token"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("page_token")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPageToken;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPageToken);
            setPageToken(refVal_setPageToken);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("limit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("limit")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setLimit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLimit);
            setLimit(refVal_setLimit);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("include_declared"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("include_declared")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIncludeDeclared;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIncludeDeclared);
            setIncludeDeclared(refVal_setIncludeDeclared);
            
        }
    }
    return ok;
}

void ListTablesRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdentityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("identity")), m_Identity));
    }
    if(m_ContextIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("context")), m_Context));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_Page_tokenIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("page_token")), m_Page_token));
    }
    if(m_LimitIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("limit")), m_Limit));
    }
    if(m_Include_declaredIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("include_declared")), m_Include_declared));
    }
}

bool ListTablesRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("identity"))))
    {
        std::shared_ptr<Identity> refVal_setIdentity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("identity"))), refVal_setIdentity );
        setIdentity(refVal_setIdentity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("context"))))
    {
        std::map<utility::string_t, utility::string_t> refVal_setContext;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("context"))), refVal_setContext );
        setContext(refVal_setContext);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        std::vector<utility::string_t> refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("page_token"))))
    {
        utility::string_t refVal_setPageToken;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("page_token"))), refVal_setPageToken );
        setPageToken(refVal_setPageToken);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("limit"))))
    {
        int32_t refVal_setLimit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("limit"))), refVal_setLimit );
        setLimit(refVal_setLimit);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("include_declared"))))
    {
        bool refVal_setIncludeDeclared;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("include_declared"))), refVal_setIncludeDeclared );
        setIncludeDeclared(refVal_setIncludeDeclared);
    }
    return ok;
}


std::shared_ptr<Identity> ListTablesRequest::getIdentity() const
{
    return m_Identity;
}


void ListTablesRequest::setIdentity(const std::shared_ptr<Identity>& value)
{
    m_Identity = value;
    m_IdentityIsSet = true;
}

bool ListTablesRequest::identityIsSet() const
{
    return m_IdentityIsSet;
}

void ListTablesRequest::unsetIdentity()
{
    m_IdentityIsSet = false;
}
std::map<utility::string_t, utility::string_t> ListTablesRequest::getContext() const
{
    return m_Context;
}


void ListTablesRequest::setContext(const std::map<utility::string_t, utility::string_t>& value)
{
    m_Context = value;
    m_ContextIsSet = true;
}

bool ListTablesRequest::contextIsSet() const
{
    return m_ContextIsSet;
}

void ListTablesRequest::unsetContext()
{
    m_ContextIsSet = false;
}
std::vector<utility::string_t> ListTablesRequest::getId() const
{
    return m_Id;
}


void ListTablesRequest::setId(const std::vector<utility::string_t>& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool ListTablesRequest::idIsSet() const
{
    return m_IdIsSet;
}

void ListTablesRequest::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t ListTablesRequest::getPageToken() const
{
    return m_Page_token;
}


void ListTablesRequest::setPageToken(const utility::string_t& value)
{
    m_Page_token = value;
    m_Page_tokenIsSet = true;
}

bool ListTablesRequest::pageTokenIsSet() const
{
    return m_Page_tokenIsSet;
}

void ListTablesRequest::unsetPage_token()
{
    m_Page_tokenIsSet = false;
}
int32_t ListTablesRequest::getLimit() const
{
    return m_Limit;
}

void ListTablesRequest::setLimit(int32_t value)
{
    m_Limit = value;
    m_LimitIsSet = true;
}

bool ListTablesRequest::limitIsSet() const
{
    return m_LimitIsSet;
}

void ListTablesRequest::unsetLimit()
{
    m_LimitIsSet = false;
}
bool ListTablesRequest::isIncludeDeclared() const
{
    return m_Include_declared;
}

void ListTablesRequest::setIncludeDeclared(bool value)
{
    m_Include_declared = value;
    m_Include_declaredIsSet = true;
}

bool ListTablesRequest::includeDeclaredIsSet() const
{
    return m_Include_declaredIsSet;
}

void ListTablesRequest::unsetInclude_declared()
{
    m_Include_declaredIsSet = false;
}

}
}
}
}


