/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "lance_namespace_rest_client/model/PartitionSpec.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

PartitionSpec::PartitionSpec()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_FieldsIsSet = false;
}

PartitionSpec::~PartitionSpec()
{
}

void PartitionSpec::validate()
{
    // TODO: implement validation
}

web::json::value PartitionSpec::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_FieldsIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("fields"))] = ModelBase::toJson(m_Fields);
    }

    return val;
}

bool PartitionSpec::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("fields"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("fields")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<PartitionField>> refVal_setFields;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFields);
            setFields(refVal_setFields);
            
        }
    }
    return ok;
}

void PartitionSpec::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_FieldsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("fields")), m_Fields));
    }
}

bool PartitionSpec::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("fields"))))
    {
        std::vector<std::shared_ptr<PartitionField>> refVal_setFields;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("fields"))), refVal_setFields );
        setFields(refVal_setFields);
    }
    return ok;
}


int32_t PartitionSpec::getId() const
{
    return m_Id;
}

void PartitionSpec::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool PartitionSpec::idIsSet() const
{
    return m_IdIsSet;
}

void PartitionSpec::unsetId()
{
    m_IdIsSet = false;
}
std::vector<std::shared_ptr<PartitionField>> PartitionSpec::getFields() const
{
    return m_Fields;
}


void PartitionSpec::setFields(const std::vector<std::shared_ptr<PartitionField>>& value)
{
    m_Fields = value;
    m_FieldsIsSet = true;
}

bool PartitionSpec::fieldsIsSet() const
{
    return m_FieldsIsSet;
}

void PartitionSpec::unsetFields()
{
    m_FieldsIsSet = false;
}

}
}
}
}


