/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "LanceNamespace/model/TableBasicStats.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

TableBasicStats::TableBasicStats()
{
    m_Num_deleted_rows = 0;
    m_Num_deleted_rowsIsSet = false;
    m_Num_fragments = 0;
    m_Num_fragmentsIsSet = false;
}

TableBasicStats::~TableBasicStats()
{
}

void TableBasicStats::validate()
{
    // TODO: implement validation
}

web::json::value TableBasicStats::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Num_deleted_rowsIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("num_deleted_rows"))] = ModelBase::toJson(m_Num_deleted_rows);
    }
    if(m_Num_fragmentsIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("num_fragments"))] = ModelBase::toJson(m_Num_fragments);
    }

    return val;
}

bool TableBasicStats::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("num_deleted_rows"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("num_deleted_rows")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setNumDeletedRows;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNumDeletedRows);
            setNumDeletedRows(refVal_setNumDeletedRows);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("num_fragments"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("num_fragments")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setNumFragments;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNumFragments);
            setNumFragments(refVal_setNumFragments);
            
        }
    }
    return ok;
}

void TableBasicStats::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Num_deleted_rowsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("num_deleted_rows")), m_Num_deleted_rows));
    }
    if(m_Num_fragmentsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("num_fragments")), m_Num_fragments));
    }
}

bool TableBasicStats::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("num_deleted_rows"))))
    {
        int32_t refVal_setNumDeletedRows;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("num_deleted_rows"))), refVal_setNumDeletedRows );
        setNumDeletedRows(refVal_setNumDeletedRows);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("num_fragments"))))
    {
        int32_t refVal_setNumFragments;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("num_fragments"))), refVal_setNumFragments );
        setNumFragments(refVal_setNumFragments);
    }
    return ok;
}


int32_t TableBasicStats::getNumDeletedRows() const
{
    return m_Num_deleted_rows;
}

void TableBasicStats::setNumDeletedRows(int32_t value)
{
    m_Num_deleted_rows = value;
    m_Num_deleted_rowsIsSet = true;
}

bool TableBasicStats::numDeletedRowsIsSet() const
{
    return m_Num_deleted_rowsIsSet;
}

void TableBasicStats::unsetNum_deleted_rows()
{
    m_Num_deleted_rowsIsSet = false;
}
int32_t TableBasicStats::getNumFragments() const
{
    return m_Num_fragments;
}

void TableBasicStats::setNumFragments(int32_t value)
{
    m_Num_fragments = value;
    m_Num_fragmentsIsSet = true;
}

bool TableBasicStats::numFragmentsIsSet() const
{
    return m_Num_fragmentsIsSet;
}

void TableBasicStats::unsetNum_fragments()
{
    m_Num_fragmentsIsSet = false;
}

}
}
}
}


