/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "lance_namespace_rest_client/model/UpdateTableTagRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

UpdateTableTagRequest::UpdateTableTagRequest()
{
    m_IdentityIsSet = false;
    m_ContextIsSet = false;
    m_IdIsSet = false;
    m_Tag = utility::conversions::to_string_t("");
    m_TagIsSet = false;
    m_Version = 0L;
    m_VersionIsSet = false;
    m_Branch = utility::conversions::to_string_t("");
    m_BranchIsSet = false;
}

UpdateTableTagRequest::~UpdateTableTagRequest()
{
}

void UpdateTableTagRequest::validate()
{
    // TODO: implement validation
}

web::json::value UpdateTableTagRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdentityIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("identity"))] = ModelBase::toJson(m_Identity);
    }
    if(m_ContextIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("context"))] = ModelBase::toJson(m_Context);
    }
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_TagIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("tag"))] = ModelBase::toJson(m_Tag);
    }
    if(m_VersionIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("version"))] = ModelBase::toJson(m_Version);
    }
    if(m_BranchIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("branch"))] = ModelBase::toJson(m_Branch);
    }

    return val;
}

bool UpdateTableTagRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("identity"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("identity")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Identity> refVal_setIdentity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIdentity);
            setIdentity(refVal_setIdentity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("context"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("context")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, utility::string_t> refVal_setContext;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContext);
            setContext(refVal_setContext);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("tag"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("tag")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTag;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTag);
            setTag(refVal_setTag);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("version"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("version")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setVersion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVersion);
            setVersion(refVal_setVersion);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("branch"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("branch")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBranch;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBranch);
            setBranch(refVal_setBranch);
            
        }
    }
    return ok;
}

void UpdateTableTagRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdentityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("identity")), m_Identity));
    }
    if(m_ContextIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("context")), m_Context));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_TagIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("tag")), m_Tag));
    }
    if(m_VersionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("version")), m_Version));
    }
    if(m_BranchIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("branch")), m_Branch));
    }
}

bool UpdateTableTagRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("identity"))))
    {
        std::shared_ptr<Identity> refVal_setIdentity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("identity"))), refVal_setIdentity );
        setIdentity(refVal_setIdentity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("context"))))
    {
        std::map<utility::string_t, utility::string_t> refVal_setContext;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("context"))), refVal_setContext );
        setContext(refVal_setContext);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        std::vector<utility::string_t> refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("tag"))))
    {
        utility::string_t refVal_setTag;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("tag"))), refVal_setTag );
        setTag(refVal_setTag);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("version"))))
    {
        int64_t refVal_setVersion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("version"))), refVal_setVersion );
        setVersion(refVal_setVersion);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("branch"))))
    {
        utility::string_t refVal_setBranch;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("branch"))), refVal_setBranch );
        setBranch(refVal_setBranch);
    }
    return ok;
}


std::shared_ptr<Identity> UpdateTableTagRequest::getIdentity() const
{
    return m_Identity;
}


void UpdateTableTagRequest::setIdentity(const std::shared_ptr<Identity>& value)
{
    m_Identity = value;
    m_IdentityIsSet = true;
}

bool UpdateTableTagRequest::identityIsSet() const
{
    return m_IdentityIsSet;
}

void UpdateTableTagRequest::unsetIdentity()
{
    m_IdentityIsSet = false;
}
std::map<utility::string_t, utility::string_t> UpdateTableTagRequest::getContext() const
{
    return m_Context;
}


void UpdateTableTagRequest::setContext(const std::map<utility::string_t, utility::string_t>& value)
{
    m_Context = value;
    m_ContextIsSet = true;
}

bool UpdateTableTagRequest::contextIsSet() const
{
    return m_ContextIsSet;
}

void UpdateTableTagRequest::unsetContext()
{
    m_ContextIsSet = false;
}
std::vector<utility::string_t> UpdateTableTagRequest::getId() const
{
    return m_Id;
}


void UpdateTableTagRequest::setId(const std::vector<utility::string_t>& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool UpdateTableTagRequest::idIsSet() const
{
    return m_IdIsSet;
}

void UpdateTableTagRequest::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t UpdateTableTagRequest::getTag() const
{
    return m_Tag;
}


void UpdateTableTagRequest::setTag(const utility::string_t& value)
{
    m_Tag = value;
    m_TagIsSet = true;
}

bool UpdateTableTagRequest::tagIsSet() const
{
    return m_TagIsSet;
}

void UpdateTableTagRequest::unsetTag()
{
    m_TagIsSet = false;
}
int64_t UpdateTableTagRequest::getVersion() const
{
    return m_Version;
}

void UpdateTableTagRequest::setVersion(int64_t value)
{
    m_Version = value;
    m_VersionIsSet = true;
}

bool UpdateTableTagRequest::versionIsSet() const
{
    return m_VersionIsSet;
}

void UpdateTableTagRequest::unsetVersion()
{
    m_VersionIsSet = false;
}
utility::string_t UpdateTableTagRequest::getBranch() const
{
    return m_Branch;
}


void UpdateTableTagRequest::setBranch(const utility::string_t& value)
{
    m_Branch = value;
    m_BranchIsSet = true;
}

bool UpdateTableTagRequest::branchIsSet() const
{
    return m_BranchIsSet;
}

void UpdateTableTagRequest::unsetBranch()
{
    m_BranchIsSet = false;
}

}
}
}
}


