/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlterTableAddColumnsRequest,
  AlterTableAddColumnsResponse,
  AnalyzeTableQueryPlanRequest,
  CountTableRowsRequest,
  CreateTableResponse,
  DeleteFromTableRequest,
  DeleteFromTableResponse,
  ErrorResponse,
  ExplainTableQueryPlanRequest,
  InsertIntoTableResponse,
  MergeInsertIntoTableResponse,
  QueryTableRequest,
  UpdateTableRequest,
  UpdateTableResponse,
} from '../models/index';
import {
    AlterTableAddColumnsRequestFromJSON,
    AlterTableAddColumnsRequestToJSON,
    AlterTableAddColumnsResponseFromJSON,
    AlterTableAddColumnsResponseToJSON,
    AnalyzeTableQueryPlanRequestFromJSON,
    AnalyzeTableQueryPlanRequestToJSON,
    CountTableRowsRequestFromJSON,
    CountTableRowsRequestToJSON,
    CreateTableResponseFromJSON,
    CreateTableResponseToJSON,
    DeleteFromTableRequestFromJSON,
    DeleteFromTableRequestToJSON,
    DeleteFromTableResponseFromJSON,
    DeleteFromTableResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ExplainTableQueryPlanRequestFromJSON,
    ExplainTableQueryPlanRequestToJSON,
    InsertIntoTableResponseFromJSON,
    InsertIntoTableResponseToJSON,
    MergeInsertIntoTableResponseFromJSON,
    MergeInsertIntoTableResponseToJSON,
    QueryTableRequestFromJSON,
    QueryTableRequestToJSON,
    UpdateTableRequestFromJSON,
    UpdateTableRequestToJSON,
    UpdateTableResponseFromJSON,
    UpdateTableResponseToJSON,
} from '../models/index';

export interface AlterTableAddColumnsOperationRequest {
    id: string;
    alterTableAddColumnsRequest: AlterTableAddColumnsRequest;
    delimiter?: string;
}

export interface AnalyzeTableQueryPlanOperationRequest {
    id: string;
    analyzeTableQueryPlanRequest: AnalyzeTableQueryPlanRequest;
    delimiter?: string;
}

export interface CountTableRowsOperationRequest {
    id: string;
    countTableRowsRequest: CountTableRowsRequest;
    delimiter?: string;
}

export interface CreateTableRequest {
    id: string;
    body: Blob;
    delimiter?: string;
    mode?: string;
}

export interface DeleteFromTableOperationRequest {
    id: string;
    deleteFromTableRequest: DeleteFromTableRequest;
    delimiter?: string;
}

export interface ExplainTableQueryPlanOperationRequest {
    id: string;
    explainTableQueryPlanRequest: ExplainTableQueryPlanRequest;
    delimiter?: string;
}

export interface InsertIntoTableRequest {
    id: string;
    body: Blob;
    delimiter?: string;
    mode?: string;
}

export interface MergeInsertIntoTableRequest {
    id: string;
    on: string;
    body: Blob;
    delimiter?: string;
    whenMatchedUpdateAll?: boolean;
    whenMatchedUpdateAllFilt?: string;
    whenNotMatchedInsertAll?: boolean;
    whenNotMatchedBySourceDelete?: boolean;
    whenNotMatchedBySourceDeleteFilt?: string;
    timeout?: string;
    useIndex?: boolean;
}

export interface QueryTableOperationRequest {
    id: string;
    queryTableRequest: QueryTableRequest;
    delimiter?: string;
}

export interface UpdateTableOperationRequest {
    id: string;
    updateTableRequest: UpdateTableRequest;
    delimiter?: string;
}

/**
 * 
 */
export class DataApi extends runtime.BaseAPI {

    /**
     * Add new columns to table `id` using SQL expressions or default values. 
     * Add new columns to table schema
     */
    async alterTableAddColumnsRaw(requestParameters: AlterTableAddColumnsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlterTableAddColumnsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling alterTableAddColumns().'
            );
        }

        if (requestParameters['alterTableAddColumnsRequest'] == null) {
            throw new runtime.RequiredError(
                'alterTableAddColumnsRequest',
                'Required parameter "alterTableAddColumnsRequest" was null or undefined when calling alterTableAddColumns().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/add_columns`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlterTableAddColumnsRequestToJSON(requestParameters['alterTableAddColumnsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlterTableAddColumnsResponseFromJSON(jsonValue));
    }

    /**
     * Add new columns to table `id` using SQL expressions or default values. 
     * Add new columns to table schema
     */
    async alterTableAddColumns(requestParameters: AlterTableAddColumnsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlterTableAddColumnsResponse> {
        const response = await this.alterTableAddColumnsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Analyze the query execution plan for a query against table `id`. Returns detailed statistics and analysis of the query execution plan.  REST NAMESPACE ONLY REST namespace returns the response as a plain string instead of the `AnalyzeTableQueryPlanResponse` JSON object. 
     * Analyze query execution plan
     */
    async analyzeTableQueryPlanRaw(requestParameters: AnalyzeTableQueryPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling analyzeTableQueryPlan().'
            );
        }

        if (requestParameters['analyzeTableQueryPlanRequest'] == null) {
            throw new runtime.RequiredError(
                'analyzeTableQueryPlanRequest',
                'Required parameter "analyzeTableQueryPlanRequest" was null or undefined when calling analyzeTableQueryPlan().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/analyze_plan`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AnalyzeTableQueryPlanRequestToJSON(requestParameters['analyzeTableQueryPlanRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Analyze the query execution plan for a query against table `id`. Returns detailed statistics and analysis of the query execution plan.  REST NAMESPACE ONLY REST namespace returns the response as a plain string instead of the `AnalyzeTableQueryPlanResponse` JSON object. 
     * Analyze query execution plan
     */
    async analyzeTableQueryPlan(requestParameters: AnalyzeTableQueryPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.analyzeTableQueryPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Count the number of rows in table `id`  REST NAMESPACE ONLY REST namespace returns the response as a plain integer instead of the `CountTableRowsResponse` JSON object. 
     * Count rows in a table
     */
    async countTableRowsRaw(requestParameters: CountTableRowsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling countTableRows().'
            );
        }

        if (requestParameters['countTableRowsRequest'] == null) {
            throw new runtime.RequiredError(
                'countTableRowsRequest',
                'Required parameter "countTableRowsRequest" was null or undefined when calling countTableRows().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/count_rows`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CountTableRowsRequestToJSON(requestParameters['countTableRowsRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Count the number of rows in table `id`  REST NAMESPACE ONLY REST namespace returns the response as a plain integer instead of the `CountTableRowsResponse` JSON object. 
     * Count rows in a table
     */
    async countTableRows(requestParameters: CountTableRowsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countTableRowsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create table `id` in the namespace with the given data in Arrow IPC stream.  The schema of the Arrow IPC stream is used as the table schema. If the stream is empty, the API creates a new empty table.  REST NAMESPACE ONLY REST namespace uses Arrow IPC stream as the request body. It passes in the `CreateTableRequest` information in the following way: - `id`: pass through path parameter of the same name - `mode`: pass through query parameter of the same name 
     * Create a table with the given name
     */
    async createTableRaw(requestParameters: CreateTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateTableResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createTable().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createTable().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        if (requestParameters['mode'] != null) {
            queryParameters['mode'] = requestParameters['mode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.apache.arrow.stream';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/create`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateTableResponseFromJSON(jsonValue));
    }

    /**
     * Create table `id` in the namespace with the given data in Arrow IPC stream.  The schema of the Arrow IPC stream is used as the table schema. If the stream is empty, the API creates a new empty table.  REST NAMESPACE ONLY REST namespace uses Arrow IPC stream as the request body. It passes in the `CreateTableRequest` information in the following way: - `id`: pass through path parameter of the same name - `mode`: pass through query parameter of the same name 
     * Create a table with the given name
     */
    async createTable(requestParameters: CreateTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateTableResponse> {
        const response = await this.createTableRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete rows from table `id`. 
     * Delete rows from a table
     */
    async deleteFromTableRaw(requestParameters: DeleteFromTableOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteFromTableResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteFromTable().'
            );
        }

        if (requestParameters['deleteFromTableRequest'] == null) {
            throw new runtime.RequiredError(
                'deleteFromTableRequest',
                'Required parameter "deleteFromTableRequest" was null or undefined when calling deleteFromTable().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/delete`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteFromTableRequestToJSON(requestParameters['deleteFromTableRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteFromTableResponseFromJSON(jsonValue));
    }

    /**
     * Delete rows from table `id`. 
     * Delete rows from a table
     */
    async deleteFromTable(requestParameters: DeleteFromTableOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteFromTableResponse> {
        const response = await this.deleteFromTableRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the query execution plan for a query against table `id`. Returns a human-readable explanation of how the query will be executed.  REST NAMESPACE ONLY REST namespace returns the response as a plain string instead of the `ExplainTableQueryPlanResponse` JSON object. 
     * Get query execution plan explanation
     */
    async explainTableQueryPlanRaw(requestParameters: ExplainTableQueryPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling explainTableQueryPlan().'
            );
        }

        if (requestParameters['explainTableQueryPlanRequest'] == null) {
            throw new runtime.RequiredError(
                'explainTableQueryPlanRequest',
                'Required parameter "explainTableQueryPlanRequest" was null or undefined when calling explainTableQueryPlan().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/explain_plan`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExplainTableQueryPlanRequestToJSON(requestParameters['explainTableQueryPlanRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get the query execution plan for a query against table `id`. Returns a human-readable explanation of how the query will be executed.  REST NAMESPACE ONLY REST namespace returns the response as a plain string instead of the `ExplainTableQueryPlanResponse` JSON object. 
     * Get query execution plan explanation
     */
    async explainTableQueryPlan(requestParameters: ExplainTableQueryPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.explainTableQueryPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Insert new records into table `id`.  REST NAMESPACE ONLY REST namespace uses Arrow IPC stream as the request body. It passes in the `InsertIntoTableRequest` information in the following way: - `id`: pass through path parameter of the same name - `mode`: pass through query parameter of the same name 
     * Insert records into a table
     */
    async insertIntoTableRaw(requestParameters: InsertIntoTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InsertIntoTableResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling insertIntoTable().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling insertIntoTable().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        if (requestParameters['mode'] != null) {
            queryParameters['mode'] = requestParameters['mode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.apache.arrow.stream';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/insert`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InsertIntoTableResponseFromJSON(jsonValue));
    }

    /**
     * Insert new records into table `id`.  REST NAMESPACE ONLY REST namespace uses Arrow IPC stream as the request body. It passes in the `InsertIntoTableRequest` information in the following way: - `id`: pass through path parameter of the same name - `mode`: pass through query parameter of the same name 
     * Insert records into a table
     */
    async insertIntoTable(requestParameters: InsertIntoTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InsertIntoTableResponse> {
        const response = await this.insertIntoTableRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Performs a merge insert (upsert) operation on table `id`. This operation updates existing rows based on a matching column and inserts new rows that don\'t match. It returns the number of rows inserted and updated.  REST NAMESPACE ONLY REST namespace uses Arrow IPC stream as the request body. It passes in the `MergeInsertIntoTableRequest` information in the following way: - `id`: pass through path parameter of the same name - `on`: pass through query parameter of the same name - `when_matched_update_all`: pass through query parameter of the same name - `when_matched_update_all_filt`: pass through query parameter of the same name - `when_not_matched_insert_all`: pass through query parameter of the same name - `when_not_matched_by_source_delete`: pass through query parameter of the same name - `when_not_matched_by_source_delete_filt`: pass through query parameter of the same name 
     * Merge insert (upsert) records into a table
     */
    async mergeInsertIntoTableRaw(requestParameters: MergeInsertIntoTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MergeInsertIntoTableResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling mergeInsertIntoTable().'
            );
        }

        if (requestParameters['on'] == null) {
            throw new runtime.RequiredError(
                'on',
                'Required parameter "on" was null or undefined when calling mergeInsertIntoTable().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling mergeInsertIntoTable().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        if (requestParameters['on'] != null) {
            queryParameters['on'] = requestParameters['on'];
        }

        if (requestParameters['whenMatchedUpdateAll'] != null) {
            queryParameters['when_matched_update_all'] = requestParameters['whenMatchedUpdateAll'];
        }

        if (requestParameters['whenMatchedUpdateAllFilt'] != null) {
            queryParameters['when_matched_update_all_filt'] = requestParameters['whenMatchedUpdateAllFilt'];
        }

        if (requestParameters['whenNotMatchedInsertAll'] != null) {
            queryParameters['when_not_matched_insert_all'] = requestParameters['whenNotMatchedInsertAll'];
        }

        if (requestParameters['whenNotMatchedBySourceDelete'] != null) {
            queryParameters['when_not_matched_by_source_delete'] = requestParameters['whenNotMatchedBySourceDelete'];
        }

        if (requestParameters['whenNotMatchedBySourceDeleteFilt'] != null) {
            queryParameters['when_not_matched_by_source_delete_filt'] = requestParameters['whenNotMatchedBySourceDeleteFilt'];
        }

        if (requestParameters['timeout'] != null) {
            queryParameters['timeout'] = requestParameters['timeout'];
        }

        if (requestParameters['useIndex'] != null) {
            queryParameters['use_index'] = requestParameters['useIndex'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.apache.arrow.stream';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/merge_insert`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MergeInsertIntoTableResponseFromJSON(jsonValue));
    }

    /**
     * Performs a merge insert (upsert) operation on table `id`. This operation updates existing rows based on a matching column and inserts new rows that don\'t match. It returns the number of rows inserted and updated.  REST NAMESPACE ONLY REST namespace uses Arrow IPC stream as the request body. It passes in the `MergeInsertIntoTableRequest` information in the following way: - `id`: pass through path parameter of the same name - `on`: pass through query parameter of the same name - `when_matched_update_all`: pass through query parameter of the same name - `when_matched_update_all_filt`: pass through query parameter of the same name - `when_not_matched_insert_all`: pass through query parameter of the same name - `when_not_matched_by_source_delete`: pass through query parameter of the same name - `when_not_matched_by_source_delete_filt`: pass through query parameter of the same name 
     * Merge insert (upsert) records into a table
     */
    async mergeInsertIntoTable(requestParameters: MergeInsertIntoTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MergeInsertIntoTableResponse> {
        const response = await this.mergeInsertIntoTableRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Query table `id` with vector search, full text search and optional SQL filtering. Returns results in Arrow IPC file or stream format.  REST NAMESPACE ONLY REST namespace returns the response as Arrow IPC file binary data instead of the `QueryTableResponse` JSON object. 
     * Query a table
     */
    async queryTableRaw(requestParameters: QueryTableOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling queryTable().'
            );
        }

        if (requestParameters['queryTableRequest'] == null) {
            throw new runtime.RequiredError(
                'queryTableRequest',
                'Required parameter "queryTableRequest" was null or undefined when calling queryTable().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/query`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryTableRequestToJSON(requestParameters['queryTableRequest']),
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Query table `id` with vector search, full text search and optional SQL filtering. Returns results in Arrow IPC file or stream format.  REST NAMESPACE ONLY REST namespace returns the response as Arrow IPC file binary data instead of the `QueryTableResponse` JSON object. 
     * Query a table
     */
    async queryTable(requestParameters: QueryTableOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.queryTableRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update existing rows in table `id`. 
     * Update rows in a table
     */
    async updateTableRaw(requestParameters: UpdateTableOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateTableResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateTable().'
            );
        }

        if (requestParameters['updateTableRequest'] == null) {
            throw new runtime.RequiredError(
                'updateTableRequest',
                'Required parameter "updateTableRequest" was null or undefined when calling updateTable().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/update`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTableRequestToJSON(requestParameters['updateTableRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateTableResponseFromJSON(jsonValue));
    }

    /**
     * Update existing rows in table `id`. 
     * Update rows in a table
     */
    async updateTable(requestParameters: UpdateTableOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateTableResponse> {
        const response = await this.updateTableRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
