/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateNamespaceRequest,
  CreateNamespaceResponse,
  DescribeNamespaceRequest,
  DescribeNamespaceResponse,
  DropNamespaceRequest,
  DropNamespaceResponse,
  ErrorResponse,
  ListNamespacesResponse,
  ListTablesResponse,
  NamespaceExistsRequest,
} from '../models/index';
import {
    CreateNamespaceRequestFromJSON,
    CreateNamespaceRequestToJSON,
    CreateNamespaceResponseFromJSON,
    CreateNamespaceResponseToJSON,
    DescribeNamespaceRequestFromJSON,
    DescribeNamespaceRequestToJSON,
    DescribeNamespaceResponseFromJSON,
    DescribeNamespaceResponseToJSON,
    DropNamespaceRequestFromJSON,
    DropNamespaceRequestToJSON,
    DropNamespaceResponseFromJSON,
    DropNamespaceResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ListNamespacesResponseFromJSON,
    ListNamespacesResponseToJSON,
    ListTablesResponseFromJSON,
    ListTablesResponseToJSON,
    NamespaceExistsRequestFromJSON,
    NamespaceExistsRequestToJSON,
} from '../models/index';

export interface CreateNamespaceOperationRequest {
    id: string;
    createNamespaceRequest: CreateNamespaceRequest;
    delimiter?: string;
}

export interface DescribeNamespaceOperationRequest {
    id: string;
    describeNamespaceRequest: DescribeNamespaceRequest;
    delimiter?: string;
}

export interface DropNamespaceOperationRequest {
    id: string;
    dropNamespaceRequest: DropNamespaceRequest;
    delimiter?: string;
}

export interface ListNamespacesRequest {
    id: string;
    delimiter?: string;
    pageToken?: string;
    limit?: number;
}

export interface ListTablesRequest {
    id: string;
    delimiter?: string;
    pageToken?: string;
    limit?: number;
}

export interface NamespaceExistsOperationRequest {
    id: string;
    namespaceExistsRequest: NamespaceExistsRequest;
    delimiter?: string;
}

/**
 * 
 */
export class NamespaceApi extends runtime.BaseAPI {

    /**
     * Create new namespace `id`.  During the creation process, the implementation may modify user-provided `properties`, such as adding additional properties like `created_at` to user-provided properties, omitting any specific property, or performing actions based on any property value. 
     * Create a new namespace
     */
    async createNamespaceRaw(requestParameters: CreateNamespaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateNamespaceResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createNamespace().'
            );
        }

        if (requestParameters['createNamespaceRequest'] == null) {
            throw new runtime.RequiredError(
                'createNamespaceRequest',
                'Required parameter "createNamespaceRequest" was null or undefined when calling createNamespace().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/namespace/{id}/create`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateNamespaceRequestToJSON(requestParameters['createNamespaceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateNamespaceResponseFromJSON(jsonValue));
    }

    /**
     * Create new namespace `id`.  During the creation process, the implementation may modify user-provided `properties`, such as adding additional properties like `created_at` to user-provided properties, omitting any specific property, or performing actions based on any property value. 
     * Create a new namespace
     */
    async createNamespace(requestParameters: CreateNamespaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateNamespaceResponse> {
        const response = await this.createNamespaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Describe the detailed information for namespace `id`. 
     * Describe a namespace
     */
    async describeNamespaceRaw(requestParameters: DescribeNamespaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DescribeNamespaceResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling describeNamespace().'
            );
        }

        if (requestParameters['describeNamespaceRequest'] == null) {
            throw new runtime.RequiredError(
                'describeNamespaceRequest',
                'Required parameter "describeNamespaceRequest" was null or undefined when calling describeNamespace().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/namespace/{id}/describe`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DescribeNamespaceRequestToJSON(requestParameters['describeNamespaceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DescribeNamespaceResponseFromJSON(jsonValue));
    }

    /**
     * Describe the detailed information for namespace `id`. 
     * Describe a namespace
     */
    async describeNamespace(requestParameters: DescribeNamespaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DescribeNamespaceResponse> {
        const response = await this.describeNamespaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Drop namespace `id` from its parent namespace. 
     * Drop a namespace
     */
    async dropNamespaceRaw(requestParameters: DropNamespaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DropNamespaceResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling dropNamespace().'
            );
        }

        if (requestParameters['dropNamespaceRequest'] == null) {
            throw new runtime.RequiredError(
                'dropNamespaceRequest',
                'Required parameter "dropNamespaceRequest" was null or undefined when calling dropNamespace().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/namespace/{id}/drop`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DropNamespaceRequestToJSON(requestParameters['dropNamespaceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DropNamespaceResponseFromJSON(jsonValue));
    }

    /**
     * Drop namespace `id` from its parent namespace. 
     * Drop a namespace
     */
    async dropNamespace(requestParameters: DropNamespaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DropNamespaceResponse> {
        const response = await this.dropNamespaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all child namespace names of the parent namespace `id`.  REST NAMESPACE ONLY REST namespace uses GET to perform this operation without a request body. It passes in the `ListNamespacesRequest` information in the following way: - `id`: pass through path parameter of the same name - `page_token`: pass through query parameter of the same name - `limit`: pass through query parameter of the same name 
     * List namespaces
     */
    async listNamespacesRaw(requestParameters: ListNamespacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListNamespacesResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listNamespaces().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/namespace/{id}/list`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListNamespacesResponseFromJSON(jsonValue));
    }

    /**
     * List all child namespace names of the parent namespace `id`.  REST NAMESPACE ONLY REST namespace uses GET to perform this operation without a request body. It passes in the `ListNamespacesRequest` information in the following way: - `id`: pass through path parameter of the same name - `page_token`: pass through query parameter of the same name - `limit`: pass through query parameter of the same name 
     * List namespaces
     */
    async listNamespaces(requestParameters: ListNamespacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListNamespacesResponse> {
        const response = await this.listNamespacesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all child table names of the parent namespace `id`.  REST NAMESPACE ONLY REST namespace uses GET to perform this operation without a request body. It passes in the `ListTablesRequest` information in the following way: - `id`: pass through path parameter of the same name - `page_token`: pass through query parameter of the same name - `limit`: pass through query parameter of the same name 
     * List tables in a namespace
     */
    async listTablesRaw(requestParameters: ListTablesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTablesResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listTables().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/namespace/{id}/table/list`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTablesResponseFromJSON(jsonValue));
    }

    /**
     * List all child table names of the parent namespace `id`.  REST NAMESPACE ONLY REST namespace uses GET to perform this operation without a request body. It passes in the `ListTablesRequest` information in the following way: - `id`: pass through path parameter of the same name - `page_token`: pass through query parameter of the same name - `limit`: pass through query parameter of the same name 
     * List tables in a namespace
     */
    async listTables(requestParameters: ListTablesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTablesResponse> {
        const response = await this.listTablesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Check if namespace `id` exists.  This operation must behave exactly like the DescribeNamespace API, except it does not contain a response body. 
     * Check if a namespace exists
     */
    async namespaceExistsRaw(requestParameters: NamespaceExistsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling namespaceExists().'
            );
        }

        if (requestParameters['namespaceExistsRequest'] == null) {
            throw new runtime.RequiredError(
                'namespaceExistsRequest',
                'Required parameter "namespaceExistsRequest" was null or undefined when calling namespaceExists().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/namespace/{id}/exists`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NamespaceExistsRequestToJSON(requestParameters['namespaceExistsRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Check if namespace `id` exists.  This operation must behave exactly like the DescribeNamespace API, except it does not contain a response body. 
     * Check if a namespace exists
     */
    async namespaceExists(requestParameters: NamespaceExistsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.namespaceExistsRaw(requestParameters, initOverrides);
    }

}
