/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTableTagRequest,
  CreateTableTagResponse,
  DeleteTableTagRequest,
  DeleteTableTagResponse,
  ErrorResponse,
  GetTableTagVersionRequest,
  GetTableTagVersionResponse,
  ListTableTagsResponse,
  UpdateTableTagRequest,
  UpdateTableTagResponse,
} from '../models/index';
import {
    CreateTableTagRequestFromJSON,
    CreateTableTagRequestToJSON,
    CreateTableTagResponseFromJSON,
    CreateTableTagResponseToJSON,
    DeleteTableTagRequestFromJSON,
    DeleteTableTagRequestToJSON,
    DeleteTableTagResponseFromJSON,
    DeleteTableTagResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetTableTagVersionRequestFromJSON,
    GetTableTagVersionRequestToJSON,
    GetTableTagVersionResponseFromJSON,
    GetTableTagVersionResponseToJSON,
    ListTableTagsResponseFromJSON,
    ListTableTagsResponseToJSON,
    UpdateTableTagRequestFromJSON,
    UpdateTableTagRequestToJSON,
    UpdateTableTagResponseFromJSON,
    UpdateTableTagResponseToJSON,
} from '../models/index';

export interface CreateTableTagOperationRequest {
    id: string;
    createTableTagRequest: CreateTableTagRequest;
    delimiter?: string;
}

export interface DeleteTableTagOperationRequest {
    id: string;
    deleteTableTagRequest: DeleteTableTagRequest;
    delimiter?: string;
}

export interface GetTableTagVersionOperationRequest {
    id: string;
    getTableTagVersionRequest: GetTableTagVersionRequest;
    delimiter?: string;
}

export interface ListTableTagsRequest {
    id: string;
    delimiter?: string;
    pageToken?: string;
    limit?: number;
}

export interface UpdateTableTagOperationRequest {
    id: string;
    updateTableTagRequest: UpdateTableTagRequest;
    delimiter?: string;
}

/**
 * 
 */
export class TagApi extends runtime.BaseAPI {

    /**
     * Create a new tag for table `id` that points to a specific version. 
     * Create a new tag
     */
    async createTableTagRaw(requestParameters: CreateTableTagOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateTableTagResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createTableTag().'
            );
        }

        if (requestParameters['createTableTagRequest'] == null) {
            throw new runtime.RequiredError(
                'createTableTagRequest',
                'Required parameter "createTableTagRequest" was null or undefined when calling createTableTag().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/tags/create`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTableTagRequestToJSON(requestParameters['createTableTagRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateTableTagResponseFromJSON(jsonValue));
    }

    /**
     * Create a new tag for table `id` that points to a specific version. 
     * Create a new tag
     */
    async createTableTag(requestParameters: CreateTableTagOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateTableTagResponse> {
        const response = await this.createTableTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an existing tag from table `id`. 
     * Delete a tag
     */
    async deleteTableTagRaw(requestParameters: DeleteTableTagOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteTableTagResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteTableTag().'
            );
        }

        if (requestParameters['deleteTableTagRequest'] == null) {
            throw new runtime.RequiredError(
                'deleteTableTagRequest',
                'Required parameter "deleteTableTagRequest" was null or undefined when calling deleteTableTag().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/tags/delete`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteTableTagRequestToJSON(requestParameters['deleteTableTagRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteTableTagResponseFromJSON(jsonValue));
    }

    /**
     * Delete an existing tag from table `id`. 
     * Delete a tag
     */
    async deleteTableTag(requestParameters: DeleteTableTagOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteTableTagResponse> {
        const response = await this.deleteTableTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the version number that a specific tag points to for table `id`. 
     * Get version for a specific tag
     */
    async getTableTagVersionRaw(requestParameters: GetTableTagVersionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTableTagVersionResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTableTagVersion().'
            );
        }

        if (requestParameters['getTableTagVersionRequest'] == null) {
            throw new runtime.RequiredError(
                'getTableTagVersionRequest',
                'Required parameter "getTableTagVersionRequest" was null or undefined when calling getTableTagVersion().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/tags/version`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetTableTagVersionRequestToJSON(requestParameters['getTableTagVersionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTableTagVersionResponseFromJSON(jsonValue));
    }

    /**
     * Get the version number that a specific tag points to for table `id`. 
     * Get version for a specific tag
     */
    async getTableTagVersion(requestParameters: GetTableTagVersionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTableTagVersionResponse> {
        const response = await this.getTableTagVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all tags that have been created for table `id`. Returns a map of tag names to their corresponding version numbers and metadata.  REST NAMESPACE ONLY REST namespace does not use a request body for this operation. The `ListTableTagsRequest` information is passed in the following way: - `id`: pass through path parameter of the same name - `page_token`: pass through query parameter of the same name - `limit`: pass through query parameter of the same name 
     * List all tags for a table
     */
    async listTableTagsRaw(requestParameters: ListTableTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTableTagsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listTableTags().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/tags/list`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTableTagsResponseFromJSON(jsonValue));
    }

    /**
     * List all tags that have been created for table `id`. Returns a map of tag names to their corresponding version numbers and metadata.  REST NAMESPACE ONLY REST namespace does not use a request body for this operation. The `ListTableTagsRequest` information is passed in the following way: - `id`: pass through path parameter of the same name - `page_token`: pass through query parameter of the same name - `limit`: pass through query parameter of the same name 
     * List all tags for a table
     */
    async listTableTags(requestParameters: ListTableTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTableTagsResponse> {
        const response = await this.listTableTagsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing tag for table `id` to point to a different version. 
     * Update a tag to point to a different version
     */
    async updateTableTagRaw(requestParameters: UpdateTableTagOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateTableTagResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateTableTag().'
            );
        }

        if (requestParameters['updateTableTagRequest'] == null) {
            throw new runtime.RequiredError(
                'updateTableTagRequest',
                'Required parameter "updateTableTagRequest" was null or undefined when calling updateTableTag().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delimiter'] != null) {
            queryParameters['delimiter'] = requestParameters['delimiter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/table/{id}/tags/update`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTableTagRequestToJSON(requestParameters['updateTableTagRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateTableTagResponseFromJSON(jsonValue));
    }

    /**
     * Update an existing tag for table `id` to point to a different version. 
     * Update a tag to point to a different version
     */
    async updateTableTag(requestParameters: UpdateTableTagOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateTableTagResponse> {
        const response = await this.updateTableTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
