[workspace]
resolver = "2"
members = ["lance-namespace", "lance-namespace-reqwest-client"]

[workspace.dependencies]
lance-namespace-reqwest-client = { path = "lance-namespace-reqwest-client", version = "0.0.12" }