/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlterTableBackfillColumnsRequest {
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Box<models::Identity>>,
    /// Table identifier path (namespace + table name)
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<Vec<String>>,
    /// Branch to target. When not specified, the main branch is used. 
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    /// Lance field path.  A field path identifies a field in a Lance schema. Nested fields are addressed by joining path segments with `.`. A `.` that is not inside backticks is always a path separator, so a field name that contains a literal `.` must be written as a backtick-quoted segment, for example `parent.`child.with.dot``. Backticks inside a quoted segment are escaped by doubling them.  The canonical display form is the full path from the table schema root to the field, with any segment containing characters other than alphanumeric characters or `_` quoted with backticks, for example `metadata.status`, `MetaData.userId`, and `meta-data`.`user-id`. Index listings and error messages should use this canonical form.  A leaf field name by itself only identifies a top-level field. Nested fields must be referenced by their full path, which keeps schemas with the same leaf name under different parents unambiguous. If a path cannot be parsed or resolved against the table schema, the implementation should reject the request with InvalidInput or TableColumnNotFound. 
    #[serde(rename = "column")]
    pub column: String,
    /// Optional WHERE clause filter
    #[serde(rename = "where", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#where: Option<Option<String>>,
    /// Optional concurrency override
    #[serde(rename = "concurrency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub concurrency: Option<Option<i32>>,
    /// Optional intra-applier concurrency override
    #[serde(rename = "intra_applier_concurrency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub intra_applier_concurrency: Option<Option<i32>>,
    /// Optional minimum checkpoint size
    #[serde(rename = "min_checkpoint_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub min_checkpoint_size: Option<Option<i32>>,
    /// Optional maximum checkpoint size
    #[serde(rename = "max_checkpoint_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_checkpoint_size: Option<Option<i32>>,
    /// Optional batch checkpoint flush interval in seconds
    #[serde(rename = "batch_checkpoint_flush_interval_seconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub batch_checkpoint_flush_interval_seconds: Option<Option<f64>>,
    /// Optional table version to read from
    #[serde(rename = "read_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub read_version: Option<Option<i32>>,
    /// Optional task size
    #[serde(rename = "task_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub task_size: Option<Option<i32>>,
    /// Optional number of fragments
    #[serde(rename = "num_frags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub num_frags: Option<Option<i32>>,
    /// Optional checkpoint size
    #[serde(rename = "checkpoint_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub checkpoint_size: Option<Option<i32>>,
    /// Optional commit granularity
    #[serde(rename = "commit_granularity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commit_granularity: Option<Option<i32>>,
    /// Optional cluster name
    #[serde(rename = "cluster", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cluster: Option<Option<String>>,
    /// Optional manifest name
    #[serde(rename = "manifest", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub manifest: Option<Option<String>>,
}

impl AlterTableBackfillColumnsRequest {
    pub fn new(column: String) -> AlterTableBackfillColumnsRequest {
        AlterTableBackfillColumnsRequest {
            identity: None,
            id: None,
            branch: None,
            column,
            r#where: None,
            concurrency: None,
            intra_applier_concurrency: None,
            min_checkpoint_size: None,
            max_checkpoint_size: None,
            batch_checkpoint_flush_interval_seconds: None,
            read_version: None,
            task_size: None,
            num_frags: None,
            checkpoint_size: None,
            commit_granularity: None,
            cluster: None,
            manifest: None,
        }
    }
}

