/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTableTagVersion404Response {
    TableNotFoundError(Box<models::TableNotFoundError>),
    TableTagNotFoundError(Box<models::TableTagNotFoundError>),
}

impl Default for GetTableTagVersion404Response {
    fn default() -> Self {
        Self::TableNotFoundError(Default::default())
    }
}
/// HTTP status code
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "404")]
    Variant404,
}

impl Default for Code {
    fn default() -> Code {
        Self::Variant404
    }
}
/// Error type identifier
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "lance-namespace:201")]
    LanceNamespaceColon201,
    #[serde(rename = "lance-namespace:401")]
    LanceNamespaceColon401,
}

impl Default for Type {
    fn default() -> Type {
        Self::LanceNamespaceColon201
    }
}

