/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BranchContents.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_BranchContents_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_BranchContents_H_


#include "LanceNamespace/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <map>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  BranchContents
    : public ModelBase
{
public:
    BranchContents();
    virtual ~BranchContents();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// BranchContents members


    /// <summary>
    /// Name of the branch this branch was created from. Absent when the branch was created from the main branch. 
    /// </summary>
    utility::string_t getParentBranch() const;
    bool parentBranchIsSet() const;
    void unsetParentBranch();
    void setParentBranch(const utility::string_t& value);

    /// <summary>
    /// Version of the parent (branch or main) this branch was created from
    /// </summary>
    int64_t getParentVersion() const;
    bool parentVersionIsSet() const;
    void unsetParentVersion();
    void setParentVersion(int64_t value);

    /// <summary>
    /// Unix timestamp (in seconds) when the branch was created
    /// </summary>
    int64_t getCreateAt() const;
    bool createAtIsSet() const;
    void unsetCreateAt();
    void setCreateAt(int64_t value);

    /// <summary>
    /// Size of the branch&#39;s manifest file in bytes
    /// </summary>
    int64_t getManifestSize() const;
    bool manifestSizeIsSet() const;
    void unsetManifestSize();
    void setManifestSize(int64_t value);

    /// <summary>
    /// Key-value metadata associated with the branch
    /// </summary>
    std::map<utility::string_t, utility::string_t> getMetadata() const;
    bool metadataIsSet() const;
    void unsetMetadata();
    void setMetadata(const std::map<utility::string_t, utility::string_t>& value);


protected:
    utility::string_t m_ParentBranch;
    bool m_ParentBranchIsSet;

    int64_t m_ParentVersion;
    bool m_ParentVersionIsSet;

    int64_t m_CreateAt;
    bool m_CreateAtIsSet;

    int64_t m_ManifestSize;
    bool m_ManifestSizeIsSet;

    std::map<utility::string_t, utility::string_t> m_Metadata;
    bool m_MetadataIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_BranchContents_H_ */
