/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CreateMaterializedViewRequest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_CreateMaterializedViewRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_CreateMaterializedViewRequest_H_

#include <stdexcept>

#include "LanceNamespace/ModelBase.h"

#include "LanceNamespace/model/Identity.h"
#include <cpprest/details/basic_types.h>
#include "LanceNamespace/model/MaterializedViewUdtfEntry.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Identity;
class MaterializedViewUdtfEntry;


class  CreateMaterializedViewRequest
    : public ModelBase
{
public:
    CreateMaterializedViewRequest();
    virtual ~CreateMaterializedViewRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// CreateMaterializedViewRequest members

    enum class KindEnum
    {
        query,
        udtf,
        chunker,
        
    };
    /// <summary>
    /// The materialized view kind. - &#x60;query&#x60; — plain query-backed view (no UDTF), 1:1 rows. - &#x60;udtf&#x60; — batch UDTF-backed view (N:M rows, full refresh). - &#x60;chunker&#x60;, aka &#39;scalar_udtf&#39; — chunker view (1:N row expansion, incremental refresh). 
    /// </summary>

    KindEnum toKindEnum(const utility::string_t& value) const;
    const utility::string_t fromKindEnum(const KindEnum value) const;


    std::shared_ptr<Identity> getIdentity() const;
    bool identityIsSet() const;
    void unsetIdentity();
    void setIdentity(const std::shared_ptr<Identity>& value);

    /// <summary>
    /// View identifier path (namespace + view name)
    /// </summary>
    std::vector<utility::string_t> getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(const std::vector<utility::string_t>& value);

    /// <summary>
    /// The materialized view kind. - &#x60;query&#x60; — plain query-backed view (no UDTF), 1:1 rows. - &#x60;udtf&#x60; — batch UDTF-backed view (N:M rows, full refresh). - &#x60;chunker&#x60;, aka &#39;scalar_udtf&#39; — chunker view (1:N row expansion, incremental refresh). 
    /// </summary>
    KindEnum getKind() const;
    bool kindIsSet() const;
    void unsetKind();
    void setKind(const KindEnum value);

    /// <summary>
    /// Opaque serialized representation of the source query that defines the view&#39;s input. The format is defined by the client; the namespace server stores it without interpreting it. 
    /// </summary>
    utility::string_t getSourceQuery() const;
    bool sourceQueryIsSet() const;
    void unsetSource_query();
    void setSourceQuery(const utility::string_t& value);

    /// <summary>
    /// Base64-encoded Arrow schema of the view output
    /// </summary>
    utility::string_t getOutputSchema() const;
    bool outputSchemaIsSet() const;
    void unsetOutput_schema();
    void setOutputSchema(const utility::string_t& value);

    std::shared_ptr<MaterializedViewUdtfEntry> getUdtfSpec() const;
    bool udtfSpecIsSet() const;
    void unsetUdtf_spec();
    void setUdtfSpec(const std::shared_ptr<MaterializedViewUdtfEntry>& value);

    /// <summary>
    /// If false, the server kicks off an initial refresh immediately after creating the view and the response includes a job ID. 
    /// </summary>
    bool isWithNoData() const;
    bool withNoDataIsSet() const;
    void unsetWith_no_data();
    void setWithNoData(bool value);

    /// <summary>
    /// If true, the view is automatically refreshed when source-table data changes past the deployment-level threshold. Boolean opt-in only; the threshold and cooldown are configured on the deployment, not per-view. 
    /// </summary>
    bool isAutoRefresh() const;
    bool autoRefreshIsSet() const;
    void unsetAuto_refresh();
    void setAutoRefresh(bool value);


protected:
    std::shared_ptr<Identity> m_Identity;
    bool m_IdentityIsSet;

    std::vector<utility::string_t> m_Id;
    bool m_IdIsSet;

    KindEnum m_Kind;
    bool m_KindIsSet;

    utility::string_t m_Source_query;
    bool m_Source_queryIsSet;

    utility::string_t m_Output_schema;
    bool m_Output_schemaIsSet;

    std::shared_ptr<MaterializedViewUdtfEntry> m_Udtf_spec;
    bool m_Udtf_specIsSet;

    bool m_With_no_data;
    bool m_With_no_dataIsSet;

    bool m_Auto_refresh;
    bool m_Auto_refreshIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_CreateMaterializedViewRequest_H_ */
