/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TagContents.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_TagContents_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_TagContents_H_


#include "LanceNamespace/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  TagContents
    : public ModelBase
{
public:
    TagContents();
    virtual ~TagContents();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// TagContents members


    /// <summary>
    /// Branch name that the tag was created on (if any)
    /// </summary>
    utility::string_t getBranch() const;
    bool branchIsSet() const;
    void unsetBranch();
    void setBranch(const utility::string_t& value);

    /// <summary>
    /// Version number that the tag points to
    /// </summary>
    int64_t getVersion() const;
    bool versionIsSet() const;
    void unsetVersion();
    void setVersion(int64_t value);

    /// <summary>
    /// Size of the manifest file in bytes
    /// </summary>
    int64_t getManifestSize() const;
    bool manifestSizeIsSet() const;
    void unsetManifestSize();
    void setManifestSize(int64_t value);


protected:
    utility::string_t m_Branch;
    bool m_BranchIsSet;

    int64_t m_Version;
    bool m_VersionIsSet;

    int64_t m_ManifestSize;
    bool m_ManifestSizeIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_TagContents_H_ */
