/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddVirtualColumnEntry
 */
export interface AddVirtualColumnEntry {
    /**
     * List of input column names for the virtual column
     * @type {Array<string>}
     * @memberof AddVirtualColumnEntry
     */
    input_columns: Array<string>;
    /**
     * Data type of the virtual column using JSON representation
     * @type {object}
     * @memberof AddVirtualColumnEntry
     */
    data_type: object;
    /**
     * Docker image to use for the UDF
     * @type {string}
     * @memberof AddVirtualColumnEntry
     */
    image: string;
    /**
     * Base64 encoded pickled UDF
     * @type {string}
     * @memberof AddVirtualColumnEntry
     */
    udf: string;
    /**
     * Name of the UDF
     * @type {string}
     * @memberof AddVirtualColumnEntry
     */
    udf_name: string;
    /**
     * Version of the UDF
     * @type {string}
     * @memberof AddVirtualColumnEntry
     */
    udf_version: string;
}

/**
 * Check if a given object implements the AddVirtualColumnEntry interface.
 */
export function instanceOfAddVirtualColumnEntry(value: object): value is AddVirtualColumnEntry {
    if (!('input_columns' in value) || value['input_columns'] === undefined) return false;
    if (!('data_type' in value) || value['data_type'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('udf' in value) || value['udf'] === undefined) return false;
    if (!('udf_name' in value) || value['udf_name'] === undefined) return false;
    if (!('udf_version' in value) || value['udf_version'] === undefined) return false;
    return true;
}

export function AddVirtualColumnEntryFromJSON(json: any): AddVirtualColumnEntry {
    return AddVirtualColumnEntryFromJSONTyped(json, false);
}

export function AddVirtualColumnEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddVirtualColumnEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'input_columns': json['input_columns'],
        'data_type': json['data_type'],
        'image': json['image'],
        'udf': json['udf'],
        'udf_name': json['udf_name'],
        'udf_version': json['udf_version'],
    };
}

export function AddVirtualColumnEntryToJSON(json: any): AddVirtualColumnEntry {
    return AddVirtualColumnEntryToJSONTyped(json, false);
}

export function AddVirtualColumnEntryToJSONTyped(value?: AddVirtualColumnEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input_columns': value['input_columns'],
        'data_type': value['data_type'],
        'image': value['image'],
        'udf': value['udf'],
        'udf_name': value['udf_name'],
        'udf_version': value['udf_version'],
    };
}

