/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlterTransactionResponse
 */
export interface AlterTransactionResponse {
    /**
     * The status of a transaction.
     * Case insensitive, supports both PascalCase and snake_case. Valid values are:
     * - Queued: the transaction is queued and not yet started
     * - Running: the transaction is currently running
     * - Succeeded: the transaction has completed successfully
     * - Failed: the transaction has failed
     * - Canceled: the transaction was canceled
     * 
     * @type {string}
     * @memberof AlterTransactionResponse
     */
    status: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AlterTransactionResponse
     */
    properties?: { [key: string]: string; };
}

/**
 * Check if a given object implements the AlterTransactionResponse interface.
 */
export function instanceOfAlterTransactionResponse(value: object): value is AlterTransactionResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AlterTransactionResponseFromJSON(json: any): AlterTransactionResponse {
    return AlterTransactionResponseFromJSONTyped(json, false);
}

export function AlterTransactionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlterTransactionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'properties': json['properties'] == null ? undefined : json['properties'],
    };
}

export function AlterTransactionResponseToJSON(json: any): AlterTransactionResponse {
    return AlterTransactionResponseToJSONTyped(json, false);
}

export function AlterTransactionResponseToJSONTyped(value?: AlterTransactionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'properties': value['properties'],
    };
}

