/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlterTransactionAction } from './AlterTransactionAction';
import {
    AlterTransactionActionFromJSON,
    AlterTransactionActionFromJSONTyped,
    AlterTransactionActionToJSON,
    AlterTransactionActionToJSONTyped,
} from './AlterTransactionAction';
import type { Identity } from './Identity';
import {
    IdentityFromJSON,
    IdentityFromJSONTyped,
    IdentityToJSON,
    IdentityToJSONTyped,
} from './Identity';

/**
 * Alter a transaction with a list of actions.
 * The server should either succeed and apply all actions, or fail and apply no action.
 * 
 * @export
 * @interface AlterTransactionRequest
 */
export interface AlterTransactionRequest {
    /**
     * 
     * @type {Identity}
     * @memberof AlterTransactionRequest
     */
    identity?: Identity;
    /**
     * Arbitrary context as key-value pairs.
     * How to use the context is custom to the specific implementation.
     * 
     * On a request, it carries caller-provided context to the implementation.
     * On a response, it carries implementation-provided context back to the caller.
     * 
     * REST NAMESPACE ONLY
     * Context entries are mapped to and from HTTP headers using the `header.` prefix:
     * - On a request, any entry whose key starts with `header.` is sent as an HTTP
     *   request header with the prefix stripped. For example, the entry
     *   `{"header.Authorization": "Bearer abc"}` is sent as the request header
     *   `Authorization: Bearer abc`.
     * - On a response, every HTTP response header is returned as an entry whose key is the
     *   header name prefixed with `header.`. For example, the response header
     *   `x-request-id: abc123` is returned as the entry `{"header.x-request-id": "abc123"}`.
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AlterTransactionRequest
     */
    context?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof AlterTransactionRequest
     */
    id?: Array<string>;
    /**
     * 
     * @type {Array<AlterTransactionAction>}
     * @memberof AlterTransactionRequest
     */
    actions: Array<AlterTransactionAction>;
}

/**
 * Check if a given object implements the AlterTransactionRequest interface.
 */
export function instanceOfAlterTransactionRequest(value: object): value is AlterTransactionRequest {
    if (!('actions' in value) || value['actions'] === undefined) return false;
    return true;
}

export function AlterTransactionRequestFromJSON(json: any): AlterTransactionRequest {
    return AlterTransactionRequestFromJSONTyped(json, false);
}

export function AlterTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlterTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'identity': json['identity'] == null ? undefined : IdentityFromJSON(json['identity']),
        'context': json['context'] == null ? undefined : json['context'],
        'id': json['id'] == null ? undefined : json['id'],
        'actions': ((json['actions'] as Array<any>).map(AlterTransactionActionFromJSON)),
    };
}

export function AlterTransactionRequestToJSON(json: any): AlterTransactionRequest {
    return AlterTransactionRequestToJSONTyped(json, false);
}

export function AlterTransactionRequestToJSONTyped(value?: AlterTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identity': IdentityToJSON(value['identity']),
        'context': value['context'],
        'id': value['id'],
        'actions': ((value['actions'] as Array<any>).map(AlterTransactionActionToJSON)),
    };
}

