/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryTableRequestFullTextQuery } from './QueryTableRequestFullTextQuery';
import {
    QueryTableRequestFullTextQueryFromJSON,
    QueryTableRequestFullTextQueryFromJSONTyped,
    QueryTableRequestFullTextQueryToJSON,
    QueryTableRequestFullTextQueryToJSONTyped,
} from './QueryTableRequestFullTextQuery';
import type { QueryTableRequestColumns } from './QueryTableRequestColumns';
import {
    QueryTableRequestColumnsFromJSON,
    QueryTableRequestColumnsFromJSONTyped,
    QueryTableRequestColumnsToJSON,
    QueryTableRequestColumnsToJSONTyped,
} from './QueryTableRequestColumns';
import type { Identity } from './Identity';
import {
    IdentityFromJSON,
    IdentityFromJSONTyped,
    IdentityToJSON,
    IdentityToJSONTyped,
} from './Identity';
import type { QueryTableRequestVector } from './QueryTableRequestVector';
import {
    QueryTableRequestVectorFromJSON,
    QueryTableRequestVectorFromJSONTyped,
    QueryTableRequestVectorToJSON,
    QueryTableRequestVectorToJSONTyped,
} from './QueryTableRequestVector';

/**
 * 
 * @export
 * @interface AnalyzeTableQueryPlanRequest
 */
export interface AnalyzeTableQueryPlanRequest {
    /**
     * 
     * @type {Identity}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    identity?: Identity;
    /**
     * Arbitrary context as key-value pairs.
     * How to use the context is custom to the specific implementation.
     * 
     * On a request, it carries caller-provided context to the implementation.
     * On a response, it carries implementation-provided context back to the caller.
     * 
     * REST NAMESPACE ONLY
     * Context entries are mapped to and from HTTP headers using the `header.` prefix:
     * - On a request, any entry whose key starts with `header.` is sent as an HTTP
     *   request header with the prefix stripped. For example, the entry
     *   `{"header.Authorization": "Bearer abc"}` is sent as the request header
     *   `Authorization: Bearer abc`.
     * - On a response, every HTTP response header is returned as an entry whose key is the
     *   header name prefixed with `header.`. For example, the response header
     *   `x-request-id: abc123` is returned as the entry `{"header.x-request-id": "abc123"}`.
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    context?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    id?: Array<string>;
    /**
     * Branch to target. When not specified, the main branch is used.
     * 
     * @type {string}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    branch?: string;
    /**
     * Whether to bypass vector index
     * @type {boolean}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    bypass_vector_index?: boolean;
    /**
     * 
     * @type {QueryTableRequestColumns}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    columns?: QueryTableRequestColumns;
    /**
     * Distance metric to use
     * @type {string}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    distance_type?: string;
    /**
     * Search effort parameter for HNSW index
     * @type {number}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    ef?: number;
    /**
     * Whether to use fast search
     * @type {boolean}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    fast_search?: boolean;
    /**
     * Optional SQL filter expression. Field references in the expression must use Lance field path syntax: nested fields use dot-separated segments, literal dots require backtick-quoted segments, and backticks inside quoted segments are doubled.
     * 
     * @type {string}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    filter?: string;
    /**
     * 
     * @type {QueryTableRequestFullTextQuery}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    full_text_query?: QueryTableRequestFullTextQuery;
    /**
     * Number of results to return
     * @type {number}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    k: number;
    /**
     * Lower bound for search
     * @type {number}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    lower_bound?: number;
    /**
     * Number of probes for IVF index
     * @type {number}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    nprobes?: number;
    /**
     * Number of results to skip
     * @type {number}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    offset?: number;
    /**
     * Whether to apply filtering before vector search
     * @type {boolean}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    prefilter?: boolean;
    /**
     * Refine factor for search
     * @type {number}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    refine_factor?: number;
    /**
     * Upper bound for search
     * @type {number}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    upper_bound?: number;
    /**
     * 
     * @type {QueryTableRequestVector}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    vector: QueryTableRequestVector;
    /**
     * Lance field path of the vector field to search. Nested fields use dot-separated segments; use backtick-quoted segments for literal dots and double backticks inside quoted segments. Use canonical full paths for display and errors; leaf names alone only identify top-level fields; invalid or unresolved paths should return InvalidInput or TableColumnNotFound.
     * @type {string}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    vector_column?: string;
    /**
     * Table version to query
     * @type {number}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    version?: number;
    /**
     * If true, return the row id as a column called `_rowid`
     * @type {boolean}
     * @memberof AnalyzeTableQueryPlanRequest
     */
    with_row_id?: boolean;
}

/**
 * Check if a given object implements the AnalyzeTableQueryPlanRequest interface.
 */
export function instanceOfAnalyzeTableQueryPlanRequest(value: object): value is AnalyzeTableQueryPlanRequest {
    if (!('k' in value) || value['k'] === undefined) return false;
    if (!('vector' in value) || value['vector'] === undefined) return false;
    return true;
}

export function AnalyzeTableQueryPlanRequestFromJSON(json: any): AnalyzeTableQueryPlanRequest {
    return AnalyzeTableQueryPlanRequestFromJSONTyped(json, false);
}

export function AnalyzeTableQueryPlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyzeTableQueryPlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'identity': json['identity'] == null ? undefined : IdentityFromJSON(json['identity']),
        'context': json['context'] == null ? undefined : json['context'],
        'id': json['id'] == null ? undefined : json['id'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'bypass_vector_index': json['bypass_vector_index'] == null ? undefined : json['bypass_vector_index'],
        'columns': json['columns'] == null ? undefined : QueryTableRequestColumnsFromJSON(json['columns']),
        'distance_type': json['distance_type'] == null ? undefined : json['distance_type'],
        'ef': json['ef'] == null ? undefined : json['ef'],
        'fast_search': json['fast_search'] == null ? undefined : json['fast_search'],
        'filter': json['filter'] == null ? undefined : json['filter'],
        'full_text_query': json['full_text_query'] == null ? undefined : QueryTableRequestFullTextQueryFromJSON(json['full_text_query']),
        'k': json['k'],
        'lower_bound': json['lower_bound'] == null ? undefined : json['lower_bound'],
        'nprobes': json['nprobes'] == null ? undefined : json['nprobes'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'prefilter': json['prefilter'] == null ? undefined : json['prefilter'],
        'refine_factor': json['refine_factor'] == null ? undefined : json['refine_factor'],
        'upper_bound': json['upper_bound'] == null ? undefined : json['upper_bound'],
        'vector': QueryTableRequestVectorFromJSON(json['vector']),
        'vector_column': json['vector_column'] == null ? undefined : json['vector_column'],
        'version': json['version'] == null ? undefined : json['version'],
        'with_row_id': json['with_row_id'] == null ? undefined : json['with_row_id'],
    };
}

export function AnalyzeTableQueryPlanRequestToJSON(json: any): AnalyzeTableQueryPlanRequest {
    return AnalyzeTableQueryPlanRequestToJSONTyped(json, false);
}

export function AnalyzeTableQueryPlanRequestToJSONTyped(value?: AnalyzeTableQueryPlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identity': IdentityToJSON(value['identity']),
        'context': value['context'],
        'id': value['id'],
        'branch': value['branch'],
        'bypass_vector_index': value['bypass_vector_index'],
        'columns': QueryTableRequestColumnsToJSON(value['columns']),
        'distance_type': value['distance_type'],
        'ef': value['ef'],
        'fast_search': value['fast_search'],
        'filter': value['filter'],
        'full_text_query': QueryTableRequestFullTextQueryToJSON(value['full_text_query']),
        'k': value['k'],
        'lower_bound': value['lower_bound'],
        'nprobes': value['nprobes'],
        'offset': value['offset'],
        'prefilter': value['prefilter'],
        'refine_factor': value['refine_factor'],
        'upper_bound': value['upper_bound'],
        'vector': QueryTableRequestVectorToJSON(value['vector']),
        'vector_column': value['vector_column'],
        'version': value['version'],
        'with_row_id': value['with_row_id'],
    };
}

