/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyzeTableQueryPlanResponse
 */
export interface AnalyzeTableQueryPlanResponse {
    /**
     * Detailed analysis of the query execution plan
     * @type {string}
     * @memberof AnalyzeTableQueryPlanResponse
     */
    analysis: string;
}

/**
 * Check if a given object implements the AnalyzeTableQueryPlanResponse interface.
 */
export function instanceOfAnalyzeTableQueryPlanResponse(value: object): value is AnalyzeTableQueryPlanResponse {
    if (!('analysis' in value) || value['analysis'] === undefined) return false;
    return true;
}

export function AnalyzeTableQueryPlanResponseFromJSON(json: any): AnalyzeTableQueryPlanResponse {
    return AnalyzeTableQueryPlanResponseFromJSONTyped(json, false);
}

export function AnalyzeTableQueryPlanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyzeTableQueryPlanResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'analysis': json['analysis'],
    };
}

export function AnalyzeTableQueryPlanResponseToJSON(json: any): AnalyzeTableQueryPlanResponse {
    return AnalyzeTableQueryPlanResponseToJSONTyped(json, false);
}

export function AnalyzeTableQueryPlanResponseToJSONTyped(value?: AnalyzeTableQueryPlanResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'analysis': value['analysis'],
    };
}

