/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FtsQuery } from './FtsQuery';
import {
    FtsQueryFromJSON,
    FtsQueryFromJSONTyped,
    FtsQueryToJSON,
    FtsQueryToJSONTyped,
} from './FtsQuery';

/**
 * Boolean query with must, should, and must_not clauses
 * @export
 * @interface BooleanQuery
 */
export interface BooleanQuery {
    /**
     * Queries that must match (AND)
     * @type {Array<FtsQuery>}
     * @memberof BooleanQuery
     */
    must: Array<FtsQuery>;
    /**
     * Queries that must not match (NOT)
     * @type {Array<FtsQuery>}
     * @memberof BooleanQuery
     */
    must_not: Array<FtsQuery>;
    /**
     * Queries that should match (OR)
     * @type {Array<FtsQuery>}
     * @memberof BooleanQuery
     */
    should: Array<FtsQuery>;
}

/**
 * Check if a given object implements the BooleanQuery interface.
 */
export function instanceOfBooleanQuery(value: object): value is BooleanQuery {
    if (!('must' in value) || value['must'] === undefined) return false;
    if (!('must_not' in value) || value['must_not'] === undefined) return false;
    if (!('should' in value) || value['should'] === undefined) return false;
    return true;
}

export function BooleanQueryFromJSON(json: any): BooleanQuery {
    return BooleanQueryFromJSONTyped(json, false);
}

export function BooleanQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooleanQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'must': ((json['must'] as Array<any>).map(FtsQueryFromJSON)),
        'must_not': ((json['must_not'] as Array<any>).map(FtsQueryFromJSON)),
        'should': ((json['should'] as Array<any>).map(FtsQueryFromJSON)),
    };
}

export function BooleanQueryToJSON(json: any): BooleanQuery {
    return BooleanQueryToJSONTyped(json, false);
}

export function BooleanQueryToJSONTyped(value?: BooleanQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'must': ((value['must'] as Array<any>).map(FtsQueryToJSON)),
        'must_not': ((value['must_not'] as Array<any>).map(FtsQueryToJSON)),
        'should': ((value['should'] as Array<any>).map(FtsQueryToJSON)),
    };
}

