/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaterializedViewUdtfEntry } from './MaterializedViewUdtfEntry';
import {
    MaterializedViewUdtfEntryFromJSON,
    MaterializedViewUdtfEntryFromJSONTyped,
    MaterializedViewUdtfEntryToJSON,
    MaterializedViewUdtfEntryToJSONTyped,
} from './MaterializedViewUdtfEntry';
import type { Identity } from './Identity';
import {
    IdentityFromJSON,
    IdentityFromJSONTyped,
    IdentityToJSON,
    IdentityToJSONTyped,
} from './Identity';

/**
 * 
 * @export
 * @interface CreateMaterializedViewRequest
 */
export interface CreateMaterializedViewRequest {
    /**
     * 
     * @type {Identity}
     * @memberof CreateMaterializedViewRequest
     */
    identity?: Identity;
    /**
     * Arbitrary context as key-value pairs.
     * How to use the context is custom to the specific implementation.
     * 
     * On a request, it carries caller-provided context to the implementation.
     * On a response, it carries implementation-provided context back to the caller.
     * 
     * REST NAMESPACE ONLY
     * Context entries are mapped to and from HTTP headers using the `header.` prefix:
     * - On a request, any entry whose key starts with `header.` is sent as an HTTP
     *   request header with the prefix stripped. For example, the entry
     *   `{"header.Authorization": "Bearer abc"}` is sent as the request header
     *   `Authorization: Bearer abc`.
     * - On a response, every HTTP response header is returned as an entry whose key is the
     *   header name prefixed with `header.`. For example, the response header
     *   `x-request-id: abc123` is returned as the entry `{"header.x-request-id": "abc123"}`.
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateMaterializedViewRequest
     */
    context?: { [key: string]: string; };
    /**
     * View identifier path (namespace + view name)
     * @type {Array<string>}
     * @memberof CreateMaterializedViewRequest
     */
    id?: Array<string>;
    /**
     * The materialized view kind.
     * - `query` — plain query-backed view (no UDTF), 1:1 rows.
     * - `udtf` — batch UDTF-backed view (N:M rows, full refresh).
     * - `chunker`, aka 'scalar_udtf' — chunker view (1:N row expansion, incremental refresh).
     * 
     * @type {string}
     * @memberof CreateMaterializedViewRequest
     */
    kind: CreateMaterializedViewRequestKindEnum;
    /**
     * Opaque serialized representation of the source query that
     * defines the view's input. The format is defined by the client;
     * the namespace server stores it without interpreting it.
     * 
     * @type {string}
     * @memberof CreateMaterializedViewRequest
     */
    source_query: string;
    /**
     * Base64-encoded Arrow schema of the view output
     * @type {string}
     * @memberof CreateMaterializedViewRequest
     */
    output_schema: string;
    /**
     * 
     * @type {MaterializedViewUdtfEntry}
     * @memberof CreateMaterializedViewRequest
     */
    udtf_spec?: MaterializedViewUdtfEntry | null;
    /**
     * If false, the server kicks off an initial refresh immediately
     * after creating the view and the response includes a job ID.
     * 
     * @type {boolean}
     * @memberof CreateMaterializedViewRequest
     */
    with_no_data?: boolean;
    /**
     * If true, the view is automatically refreshed when source-table
     * data changes past the deployment-level threshold. Boolean
     * opt-in only; the threshold and cooldown are configured on the
     * deployment, not per-view.
     * 
     * @type {boolean}
     * @memberof CreateMaterializedViewRequest
     */
    auto_refresh?: boolean | null;
}

/**
* @export
* @enum {string}
*/
export enum CreateMaterializedViewRequestKindEnum {
    Query = 'query',
    Udtf = 'udtf',
    Chunker = 'chunker'
}


/**
 * Check if a given object implements the CreateMaterializedViewRequest interface.
 */
export function instanceOfCreateMaterializedViewRequest(value: object): value is CreateMaterializedViewRequest {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('source_query' in value) || value['source_query'] === undefined) return false;
    if (!('output_schema' in value) || value['output_schema'] === undefined) return false;
    return true;
}

export function CreateMaterializedViewRequestFromJSON(json: any): CreateMaterializedViewRequest {
    return CreateMaterializedViewRequestFromJSONTyped(json, false);
}

export function CreateMaterializedViewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMaterializedViewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'identity': json['identity'] == null ? undefined : IdentityFromJSON(json['identity']),
        'context': json['context'] == null ? undefined : json['context'],
        'id': json['id'] == null ? undefined : json['id'],
        'kind': json['kind'],
        'source_query': json['source_query'],
        'output_schema': json['output_schema'],
        'udtf_spec': json['udtf_spec'] == null ? undefined : MaterializedViewUdtfEntryFromJSON(json['udtf_spec']),
        'with_no_data': json['with_no_data'] == null ? undefined : json['with_no_data'],
        'auto_refresh': json['auto_refresh'] == null ? undefined : json['auto_refresh'],
    };
}

export function CreateMaterializedViewRequestToJSON(json: any): CreateMaterializedViewRequest {
    return CreateMaterializedViewRequestToJSONTyped(json, false);
}

export function CreateMaterializedViewRequestToJSONTyped(value?: CreateMaterializedViewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identity': IdentityToJSON(value['identity']),
        'context': value['context'],
        'id': value['id'],
        'kind': value['kind'],
        'source_query': value['source_query'],
        'output_schema': value['output_schema'],
        'udtf_spec': MaterializedViewUdtfEntryToJSON(value['udtf_spec']),
        'with_no_data': value['with_no_data'],
        'auto_refresh': value['auto_refresh'],
    };
}

