/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Identity } from './Identity';
import {
    IdentityFromJSON,
    IdentityFromJSONTyped,
    IdentityToJSON,
    IdentityToJSONTyped,
} from './Identity';

/**
 * Request for declaring a table.
 * 
 * @export
 * @interface DeclareTableRequest
 */
export interface DeclareTableRequest {
    /**
     * 
     * @type {Identity}
     * @memberof DeclareTableRequest
     */
    identity?: Identity;
    /**
     * Arbitrary context for a request as key-value pairs.
     * How to use the context is custom to the specific implementation.
     * 
     * REST NAMESPACE ONLY
     * Context entries are passed via HTTP headers using the naming convention
     * `x-lance-ctx-<key>: <value>`. For example, a context entry
     * `{"trace_id": "abc123"}` would be sent as the header `x-lance-ctx-trace_id: abc123`.
     * 
     * @type {{ [key: string]: string; }}
     * @memberof DeclareTableRequest
     */
    context?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof DeclareTableRequest
     */
    id?: Array<string>;
    /**
     * Optional storage location for the table.
     * If not provided, the namespace implementation should determine the table location.
     * 
     * @type {string}
     * @memberof DeclareTableRequest
     */
    location?: string;
    /**
     * Whether to include vended credentials in the response `storage_options`.
     * When true, the implementation should provide vended credentials for accessing storage.
     * When not set, the implementation can decide whether to return vended credentials.
     * 
     * @type {boolean}
     * @memberof DeclareTableRequest
     */
    vend_credentials?: boolean;
    /**
     * Properties stored on the table, if supported by the server.
     * 
     * @type {{ [key: string]: string; }}
     * @memberof DeclareTableRequest
     */
    properties?: { [key: string]: string; };
}

/**
 * Check if a given object implements the DeclareTableRequest interface.
 */
export function instanceOfDeclareTableRequest(value: object): value is DeclareTableRequest {
    return true;
}

export function DeclareTableRequestFromJSON(json: any): DeclareTableRequest {
    return DeclareTableRequestFromJSONTyped(json, false);
}

export function DeclareTableRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeclareTableRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'identity': json['identity'] == null ? undefined : IdentityFromJSON(json['identity']),
        'context': json['context'] == null ? undefined : json['context'],
        'id': json['id'] == null ? undefined : json['id'],
        'location': json['location'] == null ? undefined : json['location'],
        'vend_credentials': json['vend_credentials'] == null ? undefined : json['vend_credentials'],
        'properties': json['properties'] == null ? undefined : json['properties'],
    };
}

export function DeclareTableRequestToJSON(json: any): DeclareTableRequest {
    return DeclareTableRequestToJSONTyped(json, false);
}

export function DeclareTableRequestToJSONTyped(value?: DeclareTableRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identity': IdentityToJSON(value['identity']),
        'context': value['context'],
        'id': value['id'],
        'location': value['location'],
        'vend_credentials': value['vend_credentials'],
        'properties': value['properties'],
    };
}

