/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for delete tag operation
 * @export
 * @interface DeleteTableTagResponse
 */
export interface DeleteTableTagResponse {
    /**
     * Optional transaction identifier
     * @type {string}
     * @memberof DeleteTableTagResponse
     */
    transaction_id?: string;
}

/**
 * Check if a given object implements the DeleteTableTagResponse interface.
 */
export function instanceOfDeleteTableTagResponse(value: object): value is DeleteTableTagResponse {
    return true;
}

export function DeleteTableTagResponseFromJSON(json: any): DeleteTableTagResponse {
    return DeleteTableTagResponseFromJSONTyped(json, false);
}

export function DeleteTableTagResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTableTagResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'transaction_id': json['transaction_id'] == null ? undefined : json['transaction_id'],
    };
}

export function DeleteTableTagResponseToJSON(json: any): DeleteTableTagResponse {
    return DeleteTableTagResponseToJSONTyped(json, false);
}

export function DeleteTableTagResponseToJSONTyped(value?: DeleteTableTagResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction_id': value['transaction_id'],
    };
}

