/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DescribeNamespaceResponse
 */
export interface DescribeNamespaceResponse {
    /**
     * Properties stored on the namespace, if supported by the server. If the server does not support namespace properties, it should return null for this field. If namespace properties are supported, but none are set, it should return an empty object.
     * @type {{ [key: string]: string; }}
     * @memberof DescribeNamespaceResponse
     */
    properties?: { [key: string]: string; };
}

/**
 * Check if a given object implements the DescribeNamespaceResponse interface.
 */
export function instanceOfDescribeNamespaceResponse(value: object): value is DescribeNamespaceResponse {
    return true;
}

export function DescribeNamespaceResponseFromJSON(json: any): DescribeNamespaceResponse {
    return DescribeNamespaceResponseFromJSONTyped(json, false);
}

export function DescribeNamespaceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DescribeNamespaceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'properties': json['properties'] == null ? undefined : json['properties'],
    };
}

export function DescribeNamespaceResponseToJSON(json: any): DescribeNamespaceResponse {
    return DescribeNamespaceResponseToJSONTyped(json, false);
}

export function DescribeNamespaceResponseToJSONTyped(value?: DescribeNamespaceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'properties': value['properties'],
    };
}

