/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Identity } from './Identity';
import {
    IdentityFromJSON,
    IdentityFromJSONTyped,
    IdentityToJSON,
    IdentityToJSONTyped,
} from './Identity';

/**
 * 
 * @export
 * @interface GetTableTagVersionRequest
 */
export interface GetTableTagVersionRequest {
    /**
     * 
     * @type {Identity}
     * @memberof GetTableTagVersionRequest
     */
    identity?: Identity;
    /**
     * Arbitrary context for a request as key-value pairs.
     * How to use the context is custom to the specific implementation.
     * 
     * REST NAMESPACE ONLY
     * Context entries are passed via HTTP headers using the naming convention
     * `x-lance-ctx-<key>: <value>`. For example, a context entry
     * `{"trace_id": "abc123"}` would be sent as the header `x-lance-ctx-trace_id: abc123`.
     * 
     * @type {{ [key: string]: string; }}
     * @memberof GetTableTagVersionRequest
     */
    context?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof GetTableTagVersionRequest
     */
    id?: Array<string>;
    /**
     * Name of the tag to get version for
     * @type {string}
     * @memberof GetTableTagVersionRequest
     */
    tag: string;
}

/**
 * Check if a given object implements the GetTableTagVersionRequest interface.
 */
export function instanceOfGetTableTagVersionRequest(value: object): value is GetTableTagVersionRequest {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    return true;
}

export function GetTableTagVersionRequestFromJSON(json: any): GetTableTagVersionRequest {
    return GetTableTagVersionRequestFromJSONTyped(json, false);
}

export function GetTableTagVersionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTableTagVersionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'identity': json['identity'] == null ? undefined : IdentityFromJSON(json['identity']),
        'context': json['context'] == null ? undefined : json['context'],
        'id': json['id'] == null ? undefined : json['id'],
        'tag': json['tag'],
    };
}

export function GetTableTagVersionRequestToJSON(json: any): GetTableTagVersionRequest {
    return GetTableTagVersionRequestToJSONTyped(json, false);
}

export function GetTableTagVersionRequestToJSONTyped(value?: GetTableTagVersionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identity': IdentityToJSON(value['identity']),
        'context': value['context'],
        'id': value['id'],
        'tag': value['tag'],
    };
}

