/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Identity } from './Identity';
import {
    IdentityFromJSON,
    IdentityFromJSONTyped,
    IdentityToJSON,
    IdentityToJSONTyped,
} from './Identity';

/**
 * 
 * @export
 * @interface RegisterTableRequest
 */
export interface RegisterTableRequest {
    /**
     * 
     * @type {Identity}
     * @memberof RegisterTableRequest
     */
    identity?: Identity;
    /**
     * Arbitrary context as key-value pairs.
     * How to use the context is custom to the specific implementation.
     * 
     * On a request, it carries caller-provided context to the implementation.
     * On a response, it carries implementation-provided context back to the caller.
     * 
     * REST NAMESPACE ONLY
     * Context entries are mapped to and from HTTP headers using the `header.` prefix:
     * - On a request, any entry whose key starts with `header.` is sent as an HTTP
     *   request header with the prefix stripped. For example, the entry
     *   `{"header.Authorization": "Bearer abc"}` is sent as the request header
     *   `Authorization: Bearer abc`.
     * - On a response, every HTTP response header is returned as an entry whose key is the
     *   header name prefixed with `header.`. For example, the response header
     *   `x-request-id: abc123` is returned as the entry `{"header.x-request-id": "abc123"}`.
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RegisterTableRequest
     */
    context?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof RegisterTableRequest
     */
    id?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RegisterTableRequest
     */
    location: string;
    /**
     * There are two modes when trying to register a table,
     * to differentiate the behavior when a table of the same name already exists.
     * Case insensitive, supports both PascalCase and snake_case. Valid values are:
     *   * Create (default): the operation fails with 409.
     *   * Overwrite: the existing table registration is replaced with the new registration.
     * 
     * @type {string}
     * @memberof RegisterTableRequest
     */
    mode?: string;
    /**
     * Properties stored on the table, if supported by the implementation.
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RegisterTableRequest
     */
    properties?: { [key: string]: string; };
}

/**
 * Check if a given object implements the RegisterTableRequest interface.
 */
export function instanceOfRegisterTableRequest(value: object): value is RegisterTableRequest {
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function RegisterTableRequestFromJSON(json: any): RegisterTableRequest {
    return RegisterTableRequestFromJSONTyped(json, false);
}

export function RegisterTableRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterTableRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'identity': json['identity'] == null ? undefined : IdentityFromJSON(json['identity']),
        'context': json['context'] == null ? undefined : json['context'],
        'id': json['id'] == null ? undefined : json['id'],
        'location': json['location'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'properties': json['properties'] == null ? undefined : json['properties'],
    };
}

export function RegisterTableRequestToJSON(json: any): RegisterTableRequest {
    return RegisterTableRequestToJSONTyped(json, false);
}

export function RegisterTableRequestToJSONTyped(value?: RegisterTableRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identity': IdentityToJSON(value['identity']),
        'context': value['context'],
        'id': value['id'],
        'location': value['location'],
        'mode': value['mode'],
        'properties': value['properties'],
    };
}

