/* tslint:disable */
/* eslint-disable */
/**
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A range of versions to delete (start inclusive, end exclusive).
 * Special values:
 * - `start_version: 0` with `end_version: -1` means ALL versions
 * 
 * @export
 * @interface VersionRange
 */
export interface VersionRange {
    /**
     * Start version of the range (inclusive).
     * Use 0 to start from the first version.
     * 
     * @type {number}
     * @memberof VersionRange
     */
    start_version: number;
    /**
     * End version of the range (exclusive).
     * Use -1 to indicate all versions up to and including the latest.
     * 
     * @type {number}
     * @memberof VersionRange
     */
    end_version: number;
}

/**
 * Check if a given object implements the VersionRange interface.
 */
export function instanceOfVersionRange(value: object): value is VersionRange {
    if (!('start_version' in value) || value['start_version'] === undefined) return false;
    if (!('end_version' in value) || value['end_version'] === undefined) return false;
    return true;
}

export function VersionRangeFromJSON(json: any): VersionRange {
    return VersionRangeFromJSONTyped(json, false);
}

export function VersionRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionRange {
    if (json == null) {
        return json;
    }
    return {
        
        'start_version': json['start_version'],
        'end_version': json['end_version'],
    };
}

export function VersionRangeToJSON(json: any): VersionRange {
    return VersionRangeToJSONTyped(json, false);
}

export function VersionRangeToJSONTyped(value?: VersionRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_version': value['start_version'],
        'end_version': value['end_version'],
    };
}

