// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors
//
// AUTO-GENERATED by ci/cts/gen_contract_tests.py.
// Source: docs/src/cts-contracts/index.yaml (operation: CreateTableScalarIndex).
// DO NOT EDIT BY HAND — run `make gen-cts-behavior` instead.

#![allow(non_snake_case)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use std::sync::Arc;

use lance_namespace_cts::{
    Capabilities, ContractCallerFactory, Fixtures, assert_contract_error, assert_contract_ok,
    models::{
        AlterTableAddColumnsRequest, AlterTableAlterColumnsRequest, AlterTableDropColumnsRequest,
        AlterTransactionRequest, AnalyzeTableQueryPlanRequest, BatchDeleteTableVersionsRequest,
        CountTableRowsRequest, CreateNamespaceRequest, CreateTableIndexRequest, CreateTableRequest,
        CreateTableTagRequest, CreateTableVersionRequest, DeleteFromTableRequest,
        DeleteTableTagRequest, DeregisterTableRequest, DescribeNamespaceRequest,
        DescribeTableIndexStatsRequest, DescribeTableRequest, DescribeTableVersionRequest,
        DescribeTransactionRequest, DropNamespaceRequest, DropTableIndexRequest, DropTableRequest,
        ExplainTableQueryPlanRequest, GetTableStatsRequest, GetTableTagVersionRequest,
        InsertIntoTableRequest, ListNamespacesRequest, ListTableIndicesRequest,
        ListTableTagsRequest, ListTableVersionsRequest, ListTablesRequest,
        MergeInsertIntoTableRequest, NamespaceExistsRequest, QueryTableRequest,
        RegisterTableRequest, RenameTableRequest, RestoreTableRequest, TableExistsRequest,
        UpdateTableRequest, UpdateTableSchemaMetadataRequest, UpdateTableTagRequest,
    },
};

async fn set_up() -> (Capabilities, Fixtures) {
    let caps = Capabilities::from_env();
    let api = ContractCallerFactory::build().await;
    let fixtures = Fixtures::new(api);
    (caps, fixtures)
}

/// CreateTableScalarIndex validates the index_type up-front and returns InvalidInput (13) when given a vector index type. dir.rs does this BEFORE any table resolution, so the case can point at a non-existent table without affecting the result.
#[tokio::test(flavor = "multi_thread")]
async fn create_scalar_index_rejects_non_scalar_type() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_indices"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: CreateTableIndexRequest = CreateTableIndexRequest {
            id: Some(vec!["TblMissing".to_string()]),
            name: Some("idx_bad".to_string()),
            column: "id".to_string(),
            index_type: "IVF_PQ".to_string(),
            ..Default::default()
        };
        let _resp = fixtures.api().create_table_scalar_index(request).await;
        assert_contract_error(&_resp, &[13]);
    }

    fixtures.tear_down().await;
}

/// With a valid scalar index_type, CreateTableScalarIndex delegates to CreateTableIndex and surfaces TableNotFound (4).
#[tokio::test(flavor = "multi_thread")]
async fn create_scalar_index_on_nonexistent_table_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_indices"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: CreateTableIndexRequest = CreateTableIndexRequest {
            id: Some(vec!["TblMissing".to_string()]),
            name: Some("idx_missing".to_string()),
            column: "id".to_string(),
            index_type: "BTREE".to_string(),
            ..Default::default()
        };
        let _resp = fixtures.api().create_table_scalar_index(request).await;
        assert_contract_error(&_resp, &[4]);
    }

    fixtures.tear_down().await;
}

/// On a real table, CreateTableScalarIndex on a missing column surfaces TableColumnNotFound (12) (delegated to create_table_index).
#[tokio::test(flavor = "multi_thread")]
async fn create_scalar_index_unknown_column_must_412() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_indices"]) {
        return;
    }

    // ─── given ──────────────────────────────────
    fixtures.create_table_empty(vec!["TblA".to_string()]).await;

    // ─── when ───────────────────────────────────────────────
    {
        let request: CreateTableIndexRequest = CreateTableIndexRequest {
            id: Some(vec!["TblA".to_string()]),
            name: Some("idx_missing_col".to_string()),
            column: "no_such_column".to_string(),
            index_type: "BTREE".to_string(),
            ..Default::default()
        };
        let _resp = fixtures.api().create_table_scalar_index(request).await;
        assert_contract_error(&_resp, &[12]);
    }

    fixtures.tear_down().await;
}

/// Duplicate index name on a scalar index → TableIndexAlreadyExists (7). Same coverage rationale as `CreateTableIndex`'s 7 case.
#[tokio::test(flavor = "multi_thread")]
async fn create_scalar_index_already_exists_must_409() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_indices", "enforces_optimistic_concurrency"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: CreateTableIndexRequest = CreateTableIndexRequest {
            id: Some(vec!["TblA".to_string()]),
            name: Some("idx_dup".to_string()),
            column: "id".to_string(),
            index_type: "BTREE".to_string(),
            ..Default::default()
        };
        let _resp = fixtures.api().create_table_scalar_index(request).await;
        assert_contract_error(&_resp, &[7]);
    }

    fixtures.tear_down().await;
}

/// See `CreateTableIndex.create_index_namespace_not_found_must_404`.
#[tokio::test(flavor = "multi_thread")]
async fn create_scalar_index_namespace_not_found_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&[
        "supports_table_indices",
        "surfaces_namespace_not_found_for_table_ops",
    ]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: CreateTableIndexRequest = CreateTableIndexRequest {
            id: Some(vec!["NsMissing".to_string(), "TblMissing".to_string()]),
            name: Some("idx_x".to_string()),
            column: "id".to_string(),
            index_type: "BTREE".to_string(),
            ..Default::default()
        };
        let _resp = fixtures.api().create_table_scalar_index(request).await;
        assert_contract_error(&_resp, &[1]);
    }

    fixtures.tear_down().await;
}

/// See `CreateTableIndex.create_index_concurrent_modification_must_409`.
#[tokio::test(flavor = "multi_thread")]
async fn create_scalar_index_concurrent_modification_must_409() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_indices", "enforces_optimistic_concurrency"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: CreateTableIndexRequest = CreateTableIndexRequest {
            id: Some(vec!["TblA".to_string()]),
            name: Some("idx_race".to_string()),
            column: "id".to_string(),
            index_type: "BTREE".to_string(),
            ..Default::default()
        };
        let _resp = fixtures.api().create_table_scalar_index(request).await;
        assert_contract_error(&_resp, &[14]);
    }

    fixtures.tear_down().await;
}
