// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors
//
// AUTO-GENERATED by ci/cts/gen_contract_tests.py.
// Source: docs/src/cts-contracts/table.yaml (operation: CreateTableVersion).
// DO NOT EDIT BY HAND — run `make gen-cts-behavior` instead.

#![allow(non_snake_case)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use std::sync::Arc;

use lance_namespace_cts::{
    Capabilities, ContractCallerFactory, Fixtures, assert_contract_error, assert_contract_ok,
    models::{
        AlterTableAddColumnsRequest, AlterTableAlterColumnsRequest, AlterTableDropColumnsRequest,
        AlterTransactionRequest, AnalyzeTableQueryPlanRequest, BatchDeleteTableVersionsRequest,
        CountTableRowsRequest, CreateNamespaceRequest, CreateTableIndexRequest, CreateTableRequest,
        CreateTableTagRequest, CreateTableVersionRequest, DeleteFromTableRequest,
        DeleteTableTagRequest, DeregisterTableRequest, DescribeNamespaceRequest,
        DescribeTableIndexStatsRequest, DescribeTableRequest, DescribeTableVersionRequest,
        DescribeTransactionRequest, DropNamespaceRequest, DropTableIndexRequest, DropTableRequest,
        ExplainTableQueryPlanRequest, GetTableStatsRequest, GetTableTagVersionRequest,
        InsertIntoTableRequest, ListNamespacesRequest, ListTableIndicesRequest,
        ListTableTagsRequest, ListTableVersionsRequest, ListTablesRequest,
        MergeInsertIntoTableRequest, NamespaceExistsRequest, QueryTableRequest,
        RegisterTableRequest, RenameTableRequest, RestoreTableRequest, TableExistsRequest,
        UpdateTableRequest, UpdateTableSchemaMetadataRequest, UpdateTableTagRequest,
    },
};

async fn set_up() -> (Capabilities, Fixtures) {
    let caps = Capabilities::from_env();
    let api = ContractCallerFactory::build().await;
    let fixtures = Fixtures::new(api);
    (caps, fixtures)
}

/// CreateTableVersion on an unknown table id surfaces TableNotFound (4) at resolve_table_location, before any object-store IO is attempted.
#[tokio::test(flavor = "multi_thread")]
async fn create_version_on_nonexistent_table_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_versioning"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: CreateTableVersionRequest = CreateTableVersionRequest {
            id: Some(vec!["TblMissing".to_string()]),
            version: 1i64,
            manifest_path: "manifest_v1.staging".to_string(),
            ..Default::default()
        };
        let _resp = fixtures.api().create_table_version(request).await;
        assert_contract_error(&_resp, &[4]);
    }

    fixtures.tear_down().await;
}

/// Two writers racing to create the same version surface ConcurrentModification (14) via the underlying object-store `copy_if_not_exists` path.
#[tokio::test(flavor = "multi_thread")]
async fn create_version_concurrent_modification_must_409() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&[
        "supports_table_versioning",
        "enforces_optimistic_concurrency",
    ]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: CreateTableVersionRequest = CreateTableVersionRequest {
            id: Some(vec!["TblA".to_string()]),
            version: 1i64,
            manifest_path: "manifest_v1.staging".to_string(),
            ..Default::default()
        };
        let _resp = fixtures.api().create_table_version(request).await;
        assert_contract_error(&_resp, &[14]);
    }

    fixtures.tear_down().await;
}

/// See `ListTables.list_tables_namespace_not_found_must_404`.
#[tokio::test(flavor = "multi_thread")]
async fn create_version_namespace_not_found_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&[
        "supports_table_versioning",
        "surfaces_namespace_not_found_for_table_ops",
    ]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: CreateTableVersionRequest = CreateTableVersionRequest {
            id: Some(vec!["NsMissing".to_string(), "TblMissing".to_string()]),
            version: 1i64,
            manifest_path: "manifest_v1.staging".to_string(),
            ..Default::default()
        };
        let _resp = fixtures.api().create_table_version(request).await;
        assert_contract_error(&_resp, &[1]);
    }

    fixtures.tear_down().await;
}
