// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors
//
// AUTO-GENERATED by ci/cts/gen_contract_tests.py.
// Source: docs/src/cts-contracts/table.yaml (operation: DropTable).
// DO NOT EDIT BY HAND — run `make gen-cts-behavior` instead.

#![allow(non_snake_case)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use std::sync::Arc;

use lance_namespace_cts::{
    Capabilities, ContractCallerFactory, Fixtures, assert_contract_error, assert_contract_ok,
    models::{
        AlterTableAddColumnsRequest, AlterTableAlterColumnsRequest, AlterTableDropColumnsRequest,
        AlterTransactionRequest, AnalyzeTableQueryPlanRequest, BatchDeleteTableVersionsRequest,
        CountTableRowsRequest, CreateNamespaceRequest, CreateTableIndexRequest, CreateTableRequest,
        CreateTableTagRequest, CreateTableVersionRequest, DeleteFromTableRequest,
        DeleteTableTagRequest, DeregisterTableRequest, DescribeNamespaceRequest,
        DescribeTableIndexStatsRequest, DescribeTableRequest, DescribeTableVersionRequest,
        DescribeTransactionRequest, DropNamespaceRequest, DropTableIndexRequest, DropTableRequest,
        ExplainTableQueryPlanRequest, GetTableStatsRequest, GetTableTagVersionRequest,
        InsertIntoTableRequest, ListNamespacesRequest, ListTableIndicesRequest,
        ListTableTagsRequest, ListTableVersionsRequest, ListTablesRequest,
        MergeInsertIntoTableRequest, NamespaceExistsRequest, QueryTableRequest,
        RegisterTableRequest, RenameTableRequest, RestoreTableRequest, TableExistsRequest,
        UpdateTableRequest, UpdateTableSchemaMetadataRequest, UpdateTableTagRequest,
    },
};

async fn set_up() -> (Capabilities, Fixtures) {
    let caps = Capabilities::from_env();
    let api = ContractCallerFactory::build().await;
    let fixtures = Fixtures::new(api);
    (caps, fixtures)
}

/// Dropping a non-existent table must return TableNotFound (4).
#[tokio::test(flavor = "multi_thread")]
async fn drop_nonexistent_table_must_404() {
    let (caps, mut fixtures) = set_up().await;

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: DropTableRequest = DropTableRequest {
            id: Some(vec!["TblMissing".to_string()]),
            ..Default::default()
        };
        let _resp = fixtures.api().drop_table(request).await;
        assert_contract_error(&_resp, &[4]);
    }

    fixtures.tear_down().await;
}

/// Dropping a created table must succeed and a subsequent TableExists call must return TableNotFound (4). Some implementations surface the post-drop existence check as the v1 disk-based Internal (18) wrapping of NotFound — it is accepted as an alternative.
#[tokio::test(flavor = "multi_thread")]
async fn drop_after_create_then_table_exists_must_404() {
    let (caps, mut fixtures) = set_up().await;

    // ─── given ──────────────────────────────────
    fixtures.create_table_empty(vec!["TblA".to_string()]).await;

    // ─── when ───────────────────────────────────────────────
    {
        let request: DropTableRequest = DropTableRequest {
            id: Some(vec!["TblA".to_string()]),
            ..Default::default()
        };
        let _resp = fixtures.api().drop_table(request).await;
        assert_contract_ok(&_resp);
    }
    {
        let request: TableExistsRequest = TableExistsRequest {
            id: Some(vec!["TblA".to_string()]),
            ..Default::default()
        };
        let _resp = fixtures.api().table_exists(request).await;
        assert_contract_error(&_resp, &[4, 18]);
    }

    fixtures.tear_down().await;
}

/// See `ListTables.list_tables_namespace_not_found_must_404`.
#[tokio::test(flavor = "multi_thread")]
async fn drop_table_namespace_not_found_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["surfaces_namespace_not_found_for_table_ops"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: DropTableRequest = DropTableRequest {
            id: Some(vec!["NsMissing".to_string(), "TblMissing".to_string()]),
            ..Default::default()
        };
        let _resp = fixtures.api().drop_table(request).await;
        assert_contract_error(&_resp, &[1]);
    }

    fixtures.tear_down().await;
}
