// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors
//
// AUTO-GENERATED by ci/cts/gen_contract_tests.py.
// Source: docs/src/cts-contracts/table.yaml (operation: InsertIntoTable).
// DO NOT EDIT BY HAND — run `make gen-cts-behavior` instead.

#![allow(non_snake_case)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use std::sync::Arc;

use lance_namespace_cts::{
    Capabilities, ContractCallerFactory, Fixtures, assert_contract_error, assert_contract_ok,
    models::{
        AlterTableAddColumnsRequest, AlterTableAlterColumnsRequest, AlterTableDropColumnsRequest,
        AlterTransactionRequest, AnalyzeTableQueryPlanRequest, BatchDeleteTableVersionsRequest,
        CountTableRowsRequest, CreateNamespaceRequest, CreateTableIndexRequest, CreateTableRequest,
        CreateTableTagRequest, CreateTableVersionRequest, DeleteFromTableRequest,
        DeleteTableTagRequest, DeregisterTableRequest, DescribeNamespaceRequest,
        DescribeTableIndexStatsRequest, DescribeTableRequest, DescribeTableVersionRequest,
        DescribeTransactionRequest, DropNamespaceRequest, DropTableIndexRequest, DropTableRequest,
        ExplainTableQueryPlanRequest, GetTableStatsRequest, GetTableTagVersionRequest,
        InsertIntoTableRequest, ListNamespacesRequest, ListTableIndicesRequest,
        ListTableTagsRequest, ListTableVersionsRequest, ListTablesRequest,
        MergeInsertIntoTableRequest, NamespaceExistsRequest, QueryTableRequest,
        RegisterTableRequest, RenameTableRequest, RestoreTableRequest, TableExistsRequest,
        UpdateTableRequest, UpdateTableSchemaMetadataRequest, UpdateTableTagRequest,
    },
};

async fn set_up() -> (Capabilities, Fixtures) {
    let caps = Capabilities::from_env();
    let api = ContractCallerFactory::build().await;
    let fixtures = Fixtures::new(api);
    (caps, fixtures)
}

/// Appending an empty Arrow IPC stream into a freshly created table is a no-op write that must succeed. This exercises the insert plumbing without depending on row-level data assertions, which are the responsibility of P4.6.
#[tokio::test(flavor = "multi_thread")]
async fn insert_append_succeeds_after_create() {
    let (caps, mut fixtures) = set_up().await;

    // ─── given ──────────────────────────────────
    fixtures.create_table_empty(vec!["TblA".to_string()]).await;

    // ─── when ───────────────────────────────────────────────
    {
        let request: InsertIntoTableRequest = InsertIntoTableRequest {
            id: Some(vec!["TblA".to_string()]),
            mode: Some("append".to_string()),
            ..Default::default()
        };
        let _resp = fixtures
            .api()
            .insert_into_table(request, Fixtures::arrow_ipc_empty())
            .await;
        assert_contract_ok(&_resp);
    }

    fixtures.tear_down().await;
}

/// InsertIntoTable against an unknown table must surface TableNotFound (4) before consuming the body.
#[tokio::test(flavor = "multi_thread")]
async fn insert_into_nonexistent_table_must_404() {
    let (caps, mut fixtures) = set_up().await;

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: InsertIntoTableRequest = InsertIntoTableRequest {
            id: Some(vec!["TblMissing".to_string()]),
            mode: Some("append".to_string()),
            ..Default::default()
        };
        let _resp = fixtures
            .api()
            .insert_into_table(request, Fixtures::arrow_ipc_empty())
            .await;
        assert_contract_error(&_resp, &[4]);
    }

    fixtures.tear_down().await;
}

/// InsertIntoTable with an unknown `mode` must return InvalidInput (13). The implementation rejects the mode before checking table existence, so the case is set up against an empty catalog.
#[tokio::test(flavor = "multi_thread")]
async fn insert_invalid_mode_must_400() {
    let (caps, mut fixtures) = set_up().await;

    // ─── given ──────────────────────────────────
    fixtures.create_table_empty(vec!["TblA".to_string()]).await;

    // ─── when ───────────────────────────────────────────────
    {
        let request: InsertIntoTableRequest = InsertIntoTableRequest {
            id: Some(vec!["TblA".to_string()]),
            mode: Some("bogus".to_string()),
            ..Default::default()
        };
        let _resp = fixtures
            .api()
            .insert_into_table(request, Fixtures::arrow_ipc_empty())
            .await;
        assert_contract_error(&_resp, &[13]);
    }

    fixtures.tear_down().await;
}

/// See `ListTables.list_tables_namespace_not_found_must_404`.
#[tokio::test(flavor = "multi_thread")]
async fn insert_into_table_namespace_not_found_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["surfaces_namespace_not_found_for_table_ops"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: InsertIntoTableRequest = InsertIntoTableRequest {
            id: Some(vec!["NsMissing".to_string(), "TblMissing".to_string()]),
            mode: Some("append".to_string()),
            ..Default::default()
        };
        let _resp = fixtures
            .api()
            .insert_into_table(request, Fixtures::arrow_ipc_empty())
            .await;
        assert_contract_error(&_resp, &[1]);
    }

    fixtures.tear_down().await;
}

/// Concurrent inserts surface ConcurrentModification (14) on OCC backends.
#[tokio::test(flavor = "multi_thread")]
async fn insert_into_table_concurrent_modification_must_409() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["enforces_optimistic_concurrency"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: InsertIntoTableRequest = InsertIntoTableRequest {
            id: Some(vec!["TblA".to_string()]),
            mode: Some("append".to_string()),
            ..Default::default()
        };
        let _resp = fixtures
            .api()
            .insert_into_table(request, Fixtures::arrow_ipc_empty())
            .await;
        assert_contract_error(&_resp, &[14]);
    }

    fixtures.tear_down().await;
}

/// InsertIntoTable against a table in an invalid state surfaces InvalidTableState (19).
#[tokio::test(flavor = "multi_thread")]
async fn insert_into_table_invalid_state_must_409() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["enforces_optimistic_concurrency"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: InsertIntoTableRequest = InsertIntoTableRequest {
            id: Some(vec!["TblA".to_string()]),
            mode: Some("append".to_string()),
            ..Default::default()
        };
        let _resp = fixtures
            .api()
            .insert_into_table(request, Fixtures::arrow_ipc_empty())
            .await;
        assert_contract_error(&_resp, &[19]);
    }

    fixtures.tear_down().await;
}

/// InsertIntoTable with an IPC body whose schema does not match the table's surfaces TableSchemaValidationError (20).
#[tokio::test(flavor = "multi_thread")]
async fn insert_into_table_invalid_schema_must_422() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["enforces_optimistic_concurrency"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: InsertIntoTableRequest = InsertIntoTableRequest {
            id: Some(vec!["TblA".to_string()]),
            mode: Some("append".to_string()),
            ..Default::default()
        };
        let _resp = fixtures
            .api()
            .insert_into_table(request, Fixtures::arrow_ipc_empty())
            .await;
        assert_contract_error(&_resp, &[20]);
    }

    fixtures.tear_down().await;
}
