// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors
//
// AUTO-GENERATED by ci/cts/gen_contract_tests.py.
// Source: docs/src/cts-contracts/table.yaml (operation: ListTableVersions).
// DO NOT EDIT BY HAND — run `make gen-cts-behavior` instead.

#![allow(non_snake_case)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use std::sync::Arc;

use lance_namespace_cts::{
    Capabilities, ContractCallerFactory, Fixtures, assert_contract_error, assert_contract_ok,
    models::{
        AlterTableAddColumnsRequest, AlterTableAlterColumnsRequest, AlterTableDropColumnsRequest,
        AlterTransactionRequest, AnalyzeTableQueryPlanRequest, BatchDeleteTableVersionsRequest,
        CountTableRowsRequest, CreateNamespaceRequest, CreateTableIndexRequest, CreateTableRequest,
        CreateTableTagRequest, CreateTableVersionRequest, DeleteFromTableRequest,
        DeleteTableTagRequest, DeregisterTableRequest, DescribeNamespaceRequest,
        DescribeTableIndexStatsRequest, DescribeTableRequest, DescribeTableVersionRequest,
        DescribeTransactionRequest, DropNamespaceRequest, DropTableIndexRequest, DropTableRequest,
        ExplainTableQueryPlanRequest, GetTableStatsRequest, GetTableTagVersionRequest,
        InsertIntoTableRequest, ListNamespacesRequest, ListTableIndicesRequest,
        ListTableTagsRequest, ListTableVersionsRequest, ListTablesRequest,
        MergeInsertIntoTableRequest, NamespaceExistsRequest, QueryTableRequest,
        RegisterTableRequest, RenameTableRequest, RestoreTableRequest, TableExistsRequest,
        UpdateTableRequest, UpdateTableSchemaMetadataRequest, UpdateTableTagRequest,
    },
};

async fn set_up() -> (Capabilities, Fixtures) {
    let caps = Capabilities::from_env();
    let api = ContractCallerFactory::build().await;
    let fixtures = Fixtures::new(api);
    (caps, fixtures)
}

/// ListTableVersions on an unknown table surfaces TableNotFound (4) at the resolve_table_location step.
#[tokio::test(flavor = "multi_thread")]
async fn list_versions_on_nonexistent_table_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_versioning"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: ListTableVersionsRequest = ListTableVersionsRequest {
            id: Some(vec!["TblMissing".to_string()]),
            ..Default::default()
        };
        let _resp = fixtures.api().list_table_versions(request).await;
        assert_contract_error(&_resp, &[4]);
    }

    fixtures.tear_down().await;
}

/// A freshly created table has at least its initial version listed; the case asserts the call succeeds.
#[tokio::test(flavor = "multi_thread")]
async fn list_versions_after_create_returns_v0() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_versioning"]) {
        return;
    }

    // ─── given ──────────────────────────────────
    fixtures.create_table_empty(vec!["TblA".to_string()]).await;

    // ─── when ───────────────────────────────────────────────
    {
        let request: ListTableVersionsRequest = ListTableVersionsRequest {
            id: Some(vec!["TblA".to_string()]),
            ..Default::default()
        };
        let _resp = fixtures.api().list_table_versions(request).await;
        assert_contract_ok(&_resp);
    }

    fixtures.tear_down().await;
}

/// See `ListTables.list_tables_namespace_not_found_must_404`.
#[tokio::test(flavor = "multi_thread")]
async fn list_versions_namespace_not_found_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&[
        "supports_table_versioning",
        "surfaces_namespace_not_found_for_table_ops",
    ]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: ListTableVersionsRequest = ListTableVersionsRequest {
            id: Some(vec!["NsMissing".to_string(), "TblMissing".to_string()]),
            ..Default::default()
        };
        let _resp = fixtures.api().list_table_versions(request).await;
        assert_contract_error(&_resp, &[1]);
    }

    fixtures.tear_down().await;
}
