// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors
//
// AUTO-GENERATED by ci/cts/gen_contract_tests.py.
// Source: docs/src/cts-contracts/data.yaml (operation: QueryTable).
// DO NOT EDIT BY HAND — run `make gen-cts-behavior` instead.

#![allow(non_snake_case)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use std::sync::Arc;

use lance_namespace_cts::{
    Capabilities, ContractCallerFactory, Fixtures, assert_contract_error, assert_contract_ok,
    models::{
        AlterTableAddColumnsRequest, AlterTableAlterColumnsRequest, AlterTableDropColumnsRequest,
        AlterTransactionRequest, AnalyzeTableQueryPlanRequest, BatchDeleteTableVersionsRequest,
        CountTableRowsRequest, CreateNamespaceRequest, CreateTableIndexRequest, CreateTableRequest,
        CreateTableTagRequest, CreateTableVersionRequest, DeleteFromTableRequest,
        DeleteTableTagRequest, DeregisterTableRequest, DescribeNamespaceRequest,
        DescribeTableIndexStatsRequest, DescribeTableRequest, DescribeTableVersionRequest,
        DescribeTransactionRequest, DropNamespaceRequest, DropTableIndexRequest, DropTableRequest,
        ExplainTableQueryPlanRequest, GetTableStatsRequest, GetTableTagVersionRequest,
        InsertIntoTableRequest, ListNamespacesRequest, ListTableIndicesRequest,
        ListTableTagsRequest, ListTableVersionsRequest, ListTablesRequest,
        MergeInsertIntoTableRequest, NamespaceExistsRequest, QueryTableRequest,
        RegisterTableRequest, RenameTableRequest, RestoreTableRequest, TableExistsRequest,
        UpdateTableRequest, UpdateTableSchemaMetadataRequest, UpdateTableTagRequest,
    },
};

async fn set_up() -> (Capabilities, Fixtures) {
    let caps = Capabilities::from_env();
    let api = ContractCallerFactory::build().await;
    let fixtures = Fixtures::new(api);
    (caps, fixtures)
}

/// QueryTable on an unknown table surfaces TableNotFound (4).
#[tokio::test(flavor = "multi_thread")]
async fn query_table_unknown_table_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_data_read"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: QueryTableRequest = QueryTableRequest {
            id: Some(vec!["TblMissing".to_string()]),
            ..Default::default()
        };
        let _resp = fixtures.api().query_table(request).await;
        assert_contract_error(&_resp, &[4]);
    }

    fixtures.tear_down().await;
}

/// QueryTable with a `filter` referencing a non-existent column surfaces TableColumnNotFound (12) at the scanner step.
#[tokio::test(flavor = "multi_thread")]
async fn query_table_unknown_column_must_412() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&[
        "supports_table_data_read",
        "enforces_optimistic_concurrency",
    ]) {
        return;
    }

    // ─── given ──────────────────────────────────
    fixtures.create_table_empty(vec!["TblA".to_string()]).await;

    // ─── when ───────────────────────────────────────────────
    {
        let request: QueryTableRequest = QueryTableRequest {
            id: Some(vec!["TblA".to_string()]),
            ..Default::default()
        };
        let _resp = fixtures.api().query_table(request).await;
        assert_contract_error(&_resp, &[12]);
    }

    fixtures.tear_down().await;
}

/// QueryTable with a non-existent `version` surfaces TableVersionNotFound (11) when the dataset loader rejects the requested version.
#[tokio::test(flavor = "multi_thread")]
async fn query_table_unknown_version_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&[
        "supports_table_data_read",
        "enforces_optimistic_concurrency",
    ]) {
        return;
    }

    // ─── given ──────────────────────────────────
    fixtures.create_table_empty(vec!["TblA".to_string()]).await;

    // ─── when ───────────────────────────────────────────────
    {
        let request: QueryTableRequest = QueryTableRequest {
            id: Some(vec!["TblA".to_string()]),
            version: Some(999i64),
            ..Default::default()
        };
        let _resp = fixtures.api().query_table(request).await;
        assert_contract_error(&_resp, &[11]);
    }

    fixtures.tear_down().await;
}

/// See `ListTableTags.list_tags_namespace_not_found_must_404`.
#[tokio::test(flavor = "multi_thread")]
async fn query_table_namespace_not_found_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&[
        "supports_table_data_read",
        "surfaces_namespace_not_found_for_table_ops",
    ]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: QueryTableRequest = QueryTableRequest {
            id: Some(vec!["NsMissing".to_string(), "TblMissing".to_string()]),
            ..Default::default()
        };
        let _resp = fixtures.api().query_table(request).await;
        assert_contract_error(&_resp, &[1]);
    }

    fixtures.tear_down().await;
}
