// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors
//
// AUTO-GENERATED by ci/cts/gen_contract_tests.py.
// Source: docs/src/cts-contracts/data.yaml (operation: UpdateTable).
// DO NOT EDIT BY HAND — run `make gen-cts-behavior` instead.

#![allow(non_snake_case)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use std::sync::Arc;

use lance_namespace_cts::{
    Capabilities, ContractCallerFactory, Fixtures, assert_contract_error, assert_contract_ok,
    models::{
        AlterTableAddColumnsRequest, AlterTableAlterColumnsRequest, AlterTableDropColumnsRequest,
        AlterTransactionRequest, AnalyzeTableQueryPlanRequest, BatchDeleteTableVersionsRequest,
        CountTableRowsRequest, CreateNamespaceRequest, CreateTableIndexRequest, CreateTableRequest,
        CreateTableTagRequest, CreateTableVersionRequest, DeleteFromTableRequest,
        DeleteTableTagRequest, DeregisterTableRequest, DescribeNamespaceRequest,
        DescribeTableIndexStatsRequest, DescribeTableRequest, DescribeTableVersionRequest,
        DescribeTransactionRequest, DropNamespaceRequest, DropTableIndexRequest, DropTableRequest,
        ExplainTableQueryPlanRequest, GetTableStatsRequest, GetTableTagVersionRequest,
        InsertIntoTableRequest, ListNamespacesRequest, ListTableIndicesRequest,
        ListTableTagsRequest, ListTableVersionsRequest, ListTablesRequest,
        MergeInsertIntoTableRequest, NamespaceExistsRequest, QueryTableRequest,
        RegisterTableRequest, RenameTableRequest, RestoreTableRequest, TableExistsRequest,
        UpdateTableRequest, UpdateTableSchemaMetadataRequest, UpdateTableTagRequest,
    },
};

async fn set_up() -> (Capabilities, Fixtures) {
    let caps = Capabilities::from_env();
    let api = ContractCallerFactory::build().await;
    let fixtures = Fixtures::new(api);
    (caps, fixtures)
}

/// UpdateTable is not implemented by dir.rs — the trait default returns Unsupported (0). Backends that opt in via `supports_update_table` instead skip this case (the capability gate fires) and provide their own coverage of codes 4 / 12 / 14 / 19 below.
#[tokio::test(flavor = "multi_thread")]
async fn update_table_unsupported_in_directory_namespace() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_update_table"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: UpdateTableRequest = UpdateTableRequest {
            id: Some(vec!["TblA".to_string()]),
            predicate: Some("id = 1".to_string()),
            ..Default::default()
        };
        let _resp = fixtures.api().update_table(request).await;
        assert_contract_error(&_resp, &[0]);
    }

    fixtures.tear_down().await;
}

/// UpdateTable on an unknown table surfaces TableNotFound (4) on backends that implement it. DirectoryNamespace skips via the capability gate.
#[tokio::test(flavor = "multi_thread")]
async fn update_table_unknown_table_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_update_table"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: UpdateTableRequest = UpdateTableRequest {
            id: Some(vec!["TblMissing".to_string()]),
            predicate: Some("id = 1".to_string()),
            ..Default::default()
        };
        let _resp = fixtures.api().update_table(request).await;
        assert_contract_error(&_resp, &[4]);
    }

    fixtures.tear_down().await;
}

/// UpdateTable referencing a non-existent column in `predicate` surfaces TableColumnNotFound (12).
#[tokio::test(flavor = "multi_thread")]
async fn update_table_unknown_column_must_412() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_update_table"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: UpdateTableRequest = UpdateTableRequest {
            id: Some(vec!["TblA".to_string()]),
            predicate: Some("no_such_column = 1".to_string()),
            ..Default::default()
        };
        let _resp = fixtures.api().update_table(request).await;
        assert_contract_error(&_resp, &[12]);
    }

    fixtures.tear_down().await;
}

/// UpdateTable from two concurrent writers surfaces ConcurrentModification (14) on OCC backends.
#[tokio::test(flavor = "multi_thread")]
async fn update_table_concurrent_modification_must_409() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_update_table", "enforces_optimistic_concurrency"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: UpdateTableRequest = UpdateTableRequest {
            id: Some(vec!["TblA".to_string()]),
            predicate: Some("id = 1".to_string()),
            ..Default::default()
        };
        let _resp = fixtures.api().update_table(request).await;
        assert_contract_error(&_resp, &[14]);
    }

    fixtures.tear_down().await;
}

/// UpdateTable against a table in an invalid state surfaces InvalidTableState (19).
#[tokio::test(flavor = "multi_thread")]
async fn update_table_invalid_state_must_409() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_update_table", "enforces_optimistic_concurrency"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: UpdateTableRequest = UpdateTableRequest {
            id: Some(vec!["TblA".to_string()]),
            predicate: Some("id = 1".to_string()),
            ..Default::default()
        };
        let _resp = fixtures.api().update_table(request).await;
        assert_contract_error(&_resp, &[19]);
    }

    fixtures.tear_down().await;
}

/// See `ListTableTags.list_tags_namespace_not_found_must_404`.
#[tokio::test(flavor = "multi_thread")]
async fn update_table_namespace_not_found_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&[
        "supports_update_table",
        "surfaces_namespace_not_found_for_table_ops",
    ]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: UpdateTableRequest = UpdateTableRequest {
            id: Some(vec!["NsMissing".to_string(), "TblMissing".to_string()]),
            predicate: Some("id = 1".to_string()),
            ..Default::default()
        };
        let _resp = fixtures.api().update_table(request).await;
        assert_contract_error(&_resp, &[1]);
    }

    fixtures.tear_down().await;
}
