// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors
//
// AUTO-GENERATED by ci/cts/gen_contract_tests.py.
// Source: docs/src/cts-contracts/tag.yaml (operation: UpdateTableTag).
// DO NOT EDIT BY HAND — run `make gen-cts-behavior` instead.

#![allow(non_snake_case)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use std::sync::Arc;

use lance_namespace_cts::{
    Capabilities, ContractCallerFactory, Fixtures, assert_contract_error, assert_contract_ok,
    models::{
        AlterTableAddColumnsRequest, AlterTableAlterColumnsRequest, AlterTableDropColumnsRequest,
        AlterTransactionRequest, AnalyzeTableQueryPlanRequest, BatchDeleteTableVersionsRequest,
        CountTableRowsRequest, CreateNamespaceRequest, CreateTableIndexRequest, CreateTableRequest,
        CreateTableTagRequest, CreateTableVersionRequest, DeleteFromTableRequest,
        DeleteTableTagRequest, DeregisterTableRequest, DescribeNamespaceRequest,
        DescribeTableIndexStatsRequest, DescribeTableRequest, DescribeTableVersionRequest,
        DescribeTransactionRequest, DropNamespaceRequest, DropTableIndexRequest, DropTableRequest,
        ExplainTableQueryPlanRequest, GetTableStatsRequest, GetTableTagVersionRequest,
        InsertIntoTableRequest, ListNamespacesRequest, ListTableIndicesRequest,
        ListTableTagsRequest, ListTableVersionsRequest, ListTablesRequest,
        MergeInsertIntoTableRequest, NamespaceExistsRequest, QueryTableRequest,
        RegisterTableRequest, RenameTableRequest, RestoreTableRequest, TableExistsRequest,
        UpdateTableRequest, UpdateTableSchemaMetadataRequest, UpdateTableTagRequest,
    },
};

async fn set_up() -> (Capabilities, Fixtures) {
    let caps = Capabilities::from_env();
    let api = ContractCallerFactory::build().await;
    let fixtures = Fixtures::new(api);
    (caps, fixtures)
}

/// UpdateTableTag on an unknown table surfaces TableNotFound (4).
#[tokio::test(flavor = "multi_thread")]
async fn update_tag_on_nonexistent_table_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_tags"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: UpdateTableTagRequest = UpdateTableTagRequest {
            id: Some(vec!["TblMissing".to_string()]),
            tag: "v1".to_string(),
            version: 2i64,
            ..Default::default()
        };
        let _resp = fixtures.api().update_table_tag(request).await;
        assert_contract_error(&_resp, &[4]);
    }

    fixtures.tear_down().await;
}

/// UpdateTableTag for an unknown tag surfaces TableTagNotFound (8).
#[tokio::test(flavor = "multi_thread")]
async fn update_tag_unknown_tag_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_tags"]) {
        return;
    }

    // ─── given ──────────────────────────────────
    fixtures.create_table_empty(vec!["TblA".to_string()]).await;

    // ─── when ───────────────────────────────────────────────
    {
        let request: UpdateTableTagRequest = UpdateTableTagRequest {
            id: Some(vec!["TblA".to_string()]),
            tag: "no_such_tag".to_string(),
            version: 1i64,
            ..Default::default()
        };
        let _resp = fixtures.api().update_table_tag(request).await;
        assert_contract_error(&_resp, &[8]);
    }

    fixtures.tear_down().await;
}

/// UpdateTableTag pointing at a missing version surfaces TableVersionNotFound (11).
#[tokio::test(flavor = "multi_thread")]
async fn update_tag_unknown_version_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_tags"]) {
        return;
    }

    // ─── given ──────────────────────────────────
    fixtures.create_table_empty(vec!["TblA".to_string()]).await;

    // ─── when ───────────────────────────────────────────────
    {
        let request: UpdateTableTagRequest = UpdateTableTagRequest {
            id: Some(vec!["TblA".to_string()]),
            tag: "v1".to_string(),
            version: 999i64,
            ..Default::default()
        };
        let _resp = fixtures.api().update_table_tag(request).await;
        assert_contract_error(&_resp, &[11]);
    }

    fixtures.tear_down().await;
}

/// Two writers racing to update the same tag surface ConcurrentModification (14) on OCC backends.
#[tokio::test(flavor = "multi_thread")]
async fn update_tag_concurrent_modification_must_409() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&["supports_table_tags", "enforces_optimistic_concurrency"]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: UpdateTableTagRequest = UpdateTableTagRequest {
            id: Some(vec!["TblA".to_string()]),
            tag: "v1".to_string(),
            version: 2i64,
            ..Default::default()
        };
        let _resp = fixtures.api().update_table_tag(request).await;
        assert_contract_error(&_resp, &[14]);
    }

    fixtures.tear_down().await;
}

/// See `ListTableTags.list_tags_namespace_not_found_must_404`.
#[tokio::test(flavor = "multi_thread")]
async fn update_tag_namespace_not_found_must_404() {
    let (caps, mut fixtures) = set_up().await;
    if caps.skip_if_missing(&[
        "supports_table_tags",
        "surfaces_namespace_not_found_for_table_ops",
    ]) {
        return;
    }

    // ─── given ──────────────────────────────────

    // ─── when ───────────────────────────────────────────────
    {
        let request: UpdateTableTagRequest = UpdateTableTagRequest {
            id: Some(vec!["NsMissing".to_string(), "TblMissing".to_string()]),
            tag: "v1".to_string(),
            version: 2i64,
            ..Default::default()
        };
        let _resp = fixtures.api().update_table_tag(request).await;
        assert_contract_error(&_resp, &[1]);
    }

    fixtures.tear_down().await;
}
