# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Java Unity Catalog Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    paths:
      - java/lance-namespace-unity/**
      - java/lance-namespace-core/**
      - .github/workflows/java-unity.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  # This env var is used by Swatinem/rust-cache@v2 for the cache
  # key, so we set it to make sure it is always consistent.
  CARGO_TERM_COLOR: always
  # Disable full debug symbol generation to speed up CI build and keep memory down
  # "1" means line tables only, which is useful for panic tracebacks.
  RUSTFLAGS: "-C debuginfo=1"
  RUST_BACKTRACE: "1"
  # according to: https://matklad.github.io/2021/09/04/fast-rust-builds.html
  # CI builds are faster with incremental disabled.
  CARGO_INCREMENTAL: "0"
  CARGO_BUILD_JOBS: "1"

jobs:
  unity-catalog-tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler libssl-dev
      # pin the toolchain version to avoid surprises
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - uses: rui314/setup-mold@v1
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Checkout lance-namespace repo
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: "maven"
      
      # Start Unity Catalog server using Docker Compose
      - name: Start Unity Catalog server
        run: |
          git clone https://github.com/unitycatalog/unitycatalog.git /tmp/unitycatalog
          cd /tmp/unitycatalog
          docker compose up -d
          # Wait for Unity Catalog to be ready
          echo "Waiting for Unity Catalog server to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/api/2.1/unity-catalog/catalogs > /dev/null; then
              echo "Unity Catalog server is ready"
              break
            fi
            echo "Waiting for Unity Catalog server... ($i/30)"
            sleep 2
          done
          # Verify server is responding
          curl -s http://localhost:8080/api/2.1/unity-catalog/catalogs || exit 1
      
      # Build dependencies first
      - name: Build dependencies
        working-directory: java
        run: mvn install -pl lance-namespace-core -am -DskipTests
      
      # Run Unity namespace tests
      - name: Run Unity Catalog tests with Java ${{ matrix.java-version }}
        working-directory: java
        run: mvn test -pl lance-namespace-unity
      
      # Clean up Docker containers
      - name: Stop Unity Catalog server
        if: always()
        run: |
          cd /tmp/unitycatalog
          docker compose down
      
      # Show Docker logs if tests failed
      - name: Show Unity Catalog logs on failure
        if: failure()
        run: |
          cd /tmp/unitycatalog
          docker compose logs