# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Python Publish

on:
  release:
    types:
      - released
  pull_request:
    paths:
      - .github/workflows/python-publish.yml
  workflow_dispatch:
    inputs:
      mode:
        description: "dry_run: build & test only, release: build & publish to PyPI"
        required: true
        default: "dry_run"
        type: choice
        options:
          - dry_run
          - release

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for PyPI trusted publishing
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install openapi-generator-cli
        run: |
          uv tool install openapi-generator-cli

      - name: Generate auto-generated Python client
        working-directory: python
        run: |
          make gen-urllib3-client

      - name: Build module dists
        working-directory: python
        run: |
          make publish

      - name: Get package versions
        id: get_versions
        run: |
          # Get urllib3_client version
          URLLIB3_VERSION=$(python -c "import tomllib; print(tomllib.load(open('python/lance_namespace_urllib3_client/pyproject.toml', 'rb'))['project']['version'])")
          echo "urllib3_version=$URLLIB3_VERSION" >> $GITHUB_OUTPUT
          
          # Get lance_namespace version
          NS_VERSION=$(python -c "import tomllib; print(tomllib.load(open('python/lance_namespace/pyproject.toml', 'rb'))['project']['version'])")
          echo "ns_version=$NS_VERSION" >> $GITHUB_OUTPUT
          
          echo "lance_namespace_urllib3_client version: $URLLIB3_VERSION"
          echo "lance_namespace version: $NS_VERSION"

      - name: Publish lance_namespace_urllib3_client to PyPI
        if: |
          (github.event_name == 'release' && github.event.action == 'released') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'release')
        working-directory: python/lance_namespace_urllib3_client
        run: |
          uv publish --trusted-publishing always
          echo "✅ Successfully published lance_namespace_urllib3_client version ${{ steps.get_versions.outputs.urllib3_version }} to PyPI!"

      - name: Publish lance_namespace to PyPI
        if: |
          (github.event_name == 'release' && github.event.action == 'released') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'release')
        working-directory: python/lance_namespace
        run: |
          uv publish --trusted-publishing always
          echo "✅ Successfully published lance_namespace version ${{ steps.get_versions.outputs.ns_version }} to PyPI!"

      - name: Verify PyPI availability
        if: |
          (github.event_name == 'release' && github.event.action == 'released') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'release')
        run: |
          echo "Waiting for packages to be available on PyPI..."
          sleep 30
          
          # Check urllib3_client
          URLLIB3_VERSION="${{ steps.get_versions.outputs.urllib3_version }}"
          if pip index versions lance-namespace-urllib3-client | grep -q "$URLLIB3_VERSION"; then
            echo "✓ lance-namespace-urllib3-client $URLLIB3_VERSION is available on PyPI"
          else
            echo "⚠️ lance-namespace-urllib3-client $URLLIB3_VERSION not yet visible on PyPI (this is normal, may take a few minutes)"
          fi
          
          # Check lance_namespace
          NS_VERSION="${{ steps.get_versions.outputs.ns_version }}"
          if pip index versions lance-namespace | grep -q "$NS_VERSION"; then
            echo "✓ lance-namespace $NS_VERSION is available on PyPI"
          else
            echo "⚠️ lance-namespace $NS_VERSION not yet visible on PyPI (this is normal, may take a few minutes)"
          fi
          
          echo ""
          echo "Users can install the packages with:"
          echo ""
          echo "pip install lance-namespace==$NS_VERSION"
          echo "pip install lance-namespace-urllib3-client==$URLLIB3_VERSION"